/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.data.json.impl.JSONArray;
import org.jfree.data.json.impl.JSONObject;

import entity.MauSac;
import entity.NhaCungCap;
import entity.NhaSanXuat;
import entity.NhaXuatBan;
import entity.Sach;
import entity.TacGia;
import entity.TheLoaiSach;
import entity.TheLoaiVanPhongPham;
import entity.VanPhongPham;
import service_impl.MauSacServiceImpl;
import service_impl.NhaCungCapServiceImpl;
import service_impl.NhaSanXuatServiceImpl;
import service_impl.NhaXuatBanServiceImpl;
import service_impl.TacGiaServiceImpl;
import service_impl.TheLoaiServiceImpl;
import service_impl.SanPhamServiceImpl;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Desktop;

/**
 *
 * @author linh
 */
public class Pnl_QuanLySanPhamV2 extends javax.swing.JPanel implements ActionListener, MouseListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JComboBox<Object> cmbLoaiVPP;
	private ArrayList<TheLoaiVanPhongPham> theLoaiVanPhongPhams;
	private ArrayList<TheLoaiSach> theLoaiSachs;
	TheLoaiServiceImpl theLoaiServiceImpl = new TheLoaiServiceImpl();
	MauSacServiceImpl mauSacServiceImpl = new MauSacServiceImpl();
	private JLabel lblSoLuongHienThi;
	private ArrayList<NhaCungCap> nhaCungCapSachs;
	private ArrayList<NhaCungCap> nhaCungCapVPPs;
	private JCheckBox chckbxHetHangVPP;
	private JButton btnDanhMucVPP;

	/**
	 * Creates new form Pnl_TimKiem
	 */
	public Pnl_QuanLySanPhamV2() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblLapPhieuDatHang = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		tbp_sanpham = new javax.swing.JTabbedPane();
		pnlTatCa = new javax.swing.JPanel();
		lblMaSP = new javax.swing.JLabel();
		lblTenSP = new javax.swing.JLabel();
		lblMauSP = new javax.swing.JLabel();
		lblGiaNhapSP = new javax.swing.JLabel();
		lblSLSP = new javax.swing.JLabel();
		txtMaSP = new javax.swing.JTextField();
		txtMauSP = new javax.swing.JTextField();
		txtTenSp = new javax.swing.JTextField();
		lblDonViSP = new javax.swing.JLabel();
		txtGiaNhapSP = new javax.swing.JTextField();
		jTextField26 = new javax.swing.JTextField();
		jTextField27 = new javax.swing.JTextField();
		lblNXBSP = new javax.swing.JLabel();
		txtNXBSP = new javax.swing.JTextField();
		scrTatca = new javax.swing.JScrollPane();
		tblTatCa = new javax.swing.JTable();
		jPanel10 = new javax.swing.JPanel();
		btnThemSP = new javax.swing.JButton();
		btnLamMoiSP = new javax.swing.JButton();
		btnCapNhatSP = new javax.swing.JButton();
		btnNhapSP = new javax.swing.JButton();
		btnXuatSP = new javax.swing.JButton();
		btnThemVpp5 = new javax.swing.JButton();
		lblNSXSP = new javax.swing.JLabel();
		txtNSXSP = new javax.swing.JTextField();
		txtTacGiaSP = new javax.swing.JTextField();
		lblTacGiaSP = new javax.swing.JLabel();
		txtNCCSP = new javax.swing.JTextField();
		lblNCCSP = new javax.swing.JLabel();
		pnlSach = new javax.swing.JPanel();
		lblMaSach = new javax.swing.JLabel();
		lblTenSach = new javax.swing.JLabel();
		lblTacGiaSach = new javax.swing.JLabel();
		lblGiaNhapSach = new javax.swing.JLabel();
		lblSLSach = new javax.swing.JLabel();
		txtMaSach = new javax.swing.JTextField();
		txtMaSach.setEditable(false);
		try {
			txtMaSach.setText(tangMaSP());
		} catch (SQLException e2) {
			// TODO Auto-generated catch block
			e2.printStackTrace();
		}
		txtTenSach = new javax.swing.JTextField();
		lblDonViSach = new javax.swing.JLabel();
		txtGiaSach = new javax.swing.JTextField();
		txtDonViSach = new javax.swing.JTextField();
		txtSoLuongSach = new javax.swing.JTextField();
		lblNCCSach = new javax.swing.JLabel();
		scrSach = new javax.swing.JScrollPane();
		tblSach = new javax.swing.JTable();
		jPanel14 = new javax.swing.JPanel();
		btnThemSach = new javax.swing.JButton();
		btnLamMoiSach = new javax.swing.JButton();
		btnDanhMucSach = new javax.swing.JButton();
		btnCapNhatSach = new javax.swing.JButton();
		btnNhapSach = new javax.swing.JButton();
		btnXuatSach = new javax.swing.JButton();
		btnLuuSach = new javax.swing.JButton();
		lblNSXSach = new javax.swing.JLabel();
		lblTheLoaiSach = new javax.swing.JLabel();
		pnlVPP = new javax.swing.JPanel();
		lblMaVPP = new javax.swing.JLabel();
		lblTenVPP = new javax.swing.JLabel();
		lblMauVPP = new javax.swing.JLabel();
		lblGiaNhapVPP = new javax.swing.JLabel();
		lblSL = new javax.swing.JLabel();
		txtMaVPP = new javax.swing.JTextField();
		txtMaVPP.setEditable(false);
		try {
			txtMaVPP.setText(tangMaSP());
		} catch (SQLException e2) {
			// TODO Auto-generated catch block
			e2.printStackTrace();
		}
		txtTenVPP = new javax.swing.JTextField();
		lblDonViVPP = new javax.swing.JLabel();
		txtGiaNhapVPP = new javax.swing.JTextField();
		txtDonViVPP = new javax.swing.JTextField();
		txtSoLuongVPP = new javax.swing.JTextField();
		lblNCCVPP = new javax.swing.JLabel();
		scrVPP = new javax.swing.JScrollPane();
		tblVPP = new javax.swing.JTable();
		jPanel13 = new javax.swing.JPanel();
		btnThemVPP = new javax.swing.JButton();
		btnLamMoiVPP = new javax.swing.JButton();
		btnCapNhatVPP = new javax.swing.JButton();
		btnNhapVPP = new javax.swing.JButton();
		btnXuatVPP = new javax.swing.JButton();
		btnLuuVPP = new javax.swing.JButton();
		lblNSXVPP = new javax.swing.JLabel();

		setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
		setPreferredSize(new java.awt.Dimension(1550, 1230));

		lblLapPhieuDatHang.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
		lblLapPhieuDatHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblLapPhieuDatHang.setText("QUẢN LÝ SẢN PHẨM");

		tbp_sanpham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		tbp_sanpham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

		lblMaSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMaSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblMaSP.setText("Mã SP:");

		lblTenSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblTenSP.setText("Tên SP:");

		lblMauSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMauSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblMauSP.setText("Màu sắc:");

		lblGiaNhapSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblGiaNhapSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblGiaNhapSP.setText("Giá nhập:");

		lblSLSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblSLSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblSLSP.setText("Số lượng:");

		txtMauSP.addActionListener(this);

		lblDonViSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblDonViSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblDonViSP.setText("Đơn vị:");

		jTextField26.addActionListener(this);

		jTextField27.addActionListener(this);

		lblNXBSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNXBSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNXBSP.setText("Nhà Xuất Bản:");

		txtNXBSP.addActionListener(this);
		String header_SanPham[] = { "STT", "M\u00E3 S\u1EA3n Ph\u1EA9m", "T\u00EAn S\u1EA3n Ph\u1EA9m",
				"S\u1ED1 l\u01B0\u1EE3ng", "\u0110\u01A1n v\u1ECB", "Gi\u00E1 Nh\u1EADp",
				"Lo\u1EA1i s\u1EA3n ph\u1EA9m", "Nh\u00E0 cung c\u1EA5p", "Nh\u00E0 s\u1EA3n xu\u1EA5t" };
		tableModel_SanPham = new DefaultTableModel(header_SanPham, 0);
		tblTatCa = new JTable(tableModel_SanPham);
//        tblTatCa.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//
//            },
//            new String [] {
//                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số lượng", "Đơn vị", "Giá Nhập", "Loại sản phẩm", "Nhà cung cấp", "Nhà sản xuất"
//            }
//        ) {
//            Class[] types = new Class [] {
//                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
//            };
//
//            public Class getColumnClass(int columnIndex) {
//                return types [columnIndex];
//            }
//        });

		scrTatca.setViewportView(tblTatCa);

		jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnThemSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnThemSP.setText("Thêm");
		btnThemSP.setToolTipText("");
		btnThemSP.setPreferredSize(new java.awt.Dimension(60, 30));
		btnThemSP.addActionListener(this);

		btnLamMoiSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnLamMoiSP.setText("Làm mới");
		btnLamMoiSP.setPreferredSize(new java.awt.Dimension(60, 30));
		btnLamMoiSP.addActionListener(this);

		btnCapNhatSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnCapNhatSP.setText("Cập nhật");
		btnCapNhatSP.setActionCommand("Sửa");
		btnCapNhatSP.addActionListener(this);

		btnNhapSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnNhapSP.setText("Nhập File");
		btnNhapSP.addActionListener(this);

		btnXuatSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnXuatSP.setText("Xuất File");
		btnXuatSP.addActionListener(this);

		btnThemVpp5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnThemVpp5.setText("Lưu");
		btnThemVpp5.addActionListener(this);

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel10Layout
				.createSequentialGroup().addGap(27)
				.addComponent(btnLamMoiSP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(54)
				.addComponent(btnThemSP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(51)
				.addComponent(btnThemVpp5, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(47)
				.addComponent(btnCapNhatSP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(51)
				.addComponent(btnNhapSP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(56)
				.addComponent(btnXuatSP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
				.addContainerGap(243, Short.MAX_VALUE)));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel10Layout.createSequentialGroup().addGap(17)
						.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(btnThemSP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLamMoiSP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCapNhatSP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnNhapSP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXuatSP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThemVpp5, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
						.addGap(20)));
		jPanel10.setLayout(jPanel10Layout);

		lblNSXSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNSXSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNSXSP.setText("Nhà Sản Xuất:");

		txtNSXSP.addActionListener(this);

		txtTacGiaSP.addActionListener(this);

		lblTacGiaSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTacGiaSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblTacGiaSP.setText("Tác giả:");

		txtNCCSP.addActionListener(this);

		lblNCCSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNCCSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNCCSP.setText("Nhà Cung Cấp");

		javax.swing.GroupLayout pnlTatCaLayout = new javax.swing.GroupLayout(pnlTatCa);
		pnlTatCa.setLayout(pnlTatCaLayout);
		pnlTatCaLayout.setHorizontalGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlTatCaLayout.createSequentialGroup().addGroup(pnlTatCaLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlTatCaLayout.createSequentialGroup().addGroup(pnlTatCaLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlTatCaLayout.createSequentialGroup().addGap(25, 25, 25)
												.addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(lblGiaNhapSP, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 82,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(lblTenSP, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 73,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(pnlTatCaLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 250,
												Short.MAX_VALUE)
										.addComponent(txtTenSp).addComponent(txtGiaNhapSP))
								.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlTatCaLayout.createSequentialGroup().addGap(117, 117, 117)
												.addGroup(pnlTatCaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(pnlTatCaLayout.createSequentialGroup()
																.addComponent(lblSLSP)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jTextField27,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 60,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(lblDonViSP)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jTextField26,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 105,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(pnlTatCaLayout.createSequentialGroup()
																.addComponent(lblTacGiaSP,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 78,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(txtTacGiaSP,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 243,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(pnlTatCaLayout.createSequentialGroup().addGap(84, 84, 84)
												.addComponent(lblNXBSP)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtNXBSP)))
								.addGap(33, 33, 33)
								.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(pnlTatCaLayout.createSequentialGroup()
												.addComponent(lblMauSP, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtMauSP, javax.swing.GroupLayout.PREFERRED_SIZE, 243,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(pnlTatCaLayout.createSequentialGroup().addComponent(lblNSXSP)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtNSXSP, javax.swing.GroupLayout.PREFERRED_SIZE, 243,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(pnlTatCaLayout.createSequentialGroup().addComponent(lblNCCSP)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtNCCSP, javax.swing.GroupLayout.PREFERRED_SIZE, 243,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 298, Short.MAX_VALUE))
						.addGroup(pnlTatCaLayout.createSequentialGroup().addContainerGap()
								.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(scrTatca, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap()));
		pnlTatCaLayout.setVerticalGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlTatCaLayout.createSequentialGroup().addGap(17, 17, 17).addGroup(pnlTatCaLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(txtNSXSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblMaSP)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtTacGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblTacGiaSP).addComponent(txtMaSP,
														javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(lblNSXSP, javax.swing.GroupLayout.Alignment.TRAILING)))
						.addGap(20, 20, 20)
						.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtMauSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblMauSP)
								.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lblTenSP)
										.addComponent(txtTenSp, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblNXBSP))
								.addComponent(txtNXBSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlTatCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlTatCaLayout.createSequentialGroup().addGap(20, 20, 20)
										.addGroup(pnlTatCaLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblGiaNhapSP).addComponent(lblSLSP)
												.addComponent(txtGiaNhapSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblDonViSP)))
								.addGroup(pnlTatCaLayout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(pnlTatCaLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtNCCSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblNCCSP).addComponent(jTextField26,
														javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(18, 18, 18)
						.addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(scrTatca, javax.swing.GroupLayout.PREFERRED_SIZE, 741,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		// tbp_sanpham.addTab("Tất cả", null, pnlTatCa, "");

		lblMaSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMaSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblMaSach.setText("Mã Sách:");

		lblTenSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTenSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblTenSach.setText("Tên Sách:");

		lblTacGiaSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTacGiaSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblTacGiaSach.setText("Tác giả:");

		lblGiaNhapSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblGiaNhapSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblGiaNhapSach.setText("Giá nhập:");
		lblGiaNhapSach.setToolTipText("");

		lblSLSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblSLSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblSLSach.setText("Số lượng:");

		lblDonViSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblDonViSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblDonViSach.setText("Đơn vị:");

		txtDonViSach.addActionListener(this);

		txtSoLuongSach.addActionListener(this);

		lblNCCSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNCCSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNCCSach.setText("NCC:");
		String header_Sach[] = { "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số lượng", "Đơn vị", "Giá Nhập",
				"Thể Loại Sách", "Nhà cung cấp", "Tác giả", "Nhà Xuất Bản" };
		tableModel_Sach = new DefaultTableModel(header_Sach, 0);
		tblSach = new JTable(tableModel_Sach);
		tblSach.addMouseListener(this);
		scrSach.setViewportView(tblSach);

		jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnThemSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnThemSach.setText("Thêm");
		btnThemSach.setToolTipText("");
		btnThemSach.setPreferredSize(new java.awt.Dimension(60, 30));
		btnThemSach.addActionListener(this);

		btnLamMoiSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnLamMoiSach.setText("Làm mới");
		btnLamMoiSach.setPreferredSize(new java.awt.Dimension(60, 30));
		btnLamMoiSach.addActionListener(this);

		btnDanhMucSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnDanhMucSach.setText("Quản lý danh mục");
		btnDanhMucSach.addActionListener(this);

		btnCapNhatSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnCapNhatSach.setText("Cập nhật");
		btnCapNhatSach.setActionCommand("Sửa");
		btnCapNhatSach.addActionListener(this);

		btnNhapSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnNhapSach.setText("Nhập File");
		btnNhapSach.addActionListener(this);

		btnXuatSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnXuatSach.setText("Xuất File");
		btnXuatSach.addActionListener(this);

		btnLuuSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnLuuSach.setText("Lưu");
		btnLuuSach.addActionListener(this);

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
		jPanel14Layout.setHorizontalGroup(jPanel14Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel14Layout
				.createSequentialGroup().addGap(27)
				.addComponent(btnLamMoiSach, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(54)
				.addComponent(btnThemSach, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(33)
				.addComponent(btnCapNhatSach, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
				.addComponent(btnDanhMucSach, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE).addGap(33)
				.addComponent(btnNhapSach, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(36)
				.addComponent(btnXuatSach, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(42)
				.addComponent(btnLuuSach, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(72)));
		jPanel14Layout.setVerticalGroup(jPanel14Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel14Layout
				.createSequentialGroup().addGap(17)
				.addGroup(jPanel14Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnThemSach, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(btnLamMoiSach, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(btnCapNhatSach, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnNhapSach, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnXuatSach, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnLuuSach, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnDanhMucSach, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
				.addGap(20)));
		jPanel14.setLayout(jPanel14Layout);

		lblNSXSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNSXSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNSXSach.setText("NXB:");

		lblTheLoaiSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTheLoaiSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblTheLoaiSach.setText("Thể Loại:");
		// Tác giả
		tacGias = new ArrayList<TacGia>();
		try {
			tacGias = tacGiaServiceImpl.getListTacGia();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbTacGia = new JComboBox<Object>();
		cmbTacGia.addItem("");
		for (TacGia tacGia : tacGias) {
			cmbTacGia.addItem(tacGia.getTenTacGia());
		}
		// Nhà Xuất bản:
		nhaXuatBans = new ArrayList<NhaXuatBan>();
		try {
			nhaXuatBans = nhaXuatBanServiceImpl.getListNhaXuatBan();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbNXB = new JComboBox<Object>();
		cmbNXB.addItem("");
		for (NhaXuatBan nhaXuatBan : nhaXuatBans) {
			cmbNXB.addItem(nhaXuatBan.getTenNXB());
		}
		// Nhà cung cấp sách
		nhaCungCaps = new ArrayList<NhaCungCap>();
		nhaCungCapSachs = new ArrayList<NhaCungCap>();
		try {
			nhaCungCapSachs = nhaCungCapServiceImpl.getListNhaCungCap("Sách");
			nhaCungCaps = nhaCungCapServiceImpl.getAllListNhaCungCap();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbNCCSach = new JComboBox<Object>();
		cmbNCCSach.addItem("");
		for (NhaCungCap nhaCungCap : nhaCungCaps) {
			cmbNCCSach.addItem(nhaCungCap.getTenNhaCungCap());
		}
		for (int i = 0; i < cmbNCCSach.getItemCount(); i++) {
			Object item = cmbNCCSach.getItemAt(i);
			System.out.println("Index: " + i + ", Value: " + item);
		}
		for (NhaCungCap nhaCungCap : nhaCungCaps) {
			int i = 0;
			System.out.println(i + nhaCungCap.getTenNhaCungCap() + "");
		}
		// Thể loại sách:
		theLoaiSachs = new ArrayList<TheLoaiSach>();
		try {
			theLoaiSachs = theLoaiServiceImpl.getListTheLoaiSach();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbLoaiSach = new JComboBox<Object>();
		cmbLoaiSach.addItem("");
		for (TheLoaiSach theLoaiSach : theLoaiSachs) {
			cmbLoaiSach.addItem(theLoaiSach.getTenLoai());
		}

		lblSoLuongHienThi = new JLabel();
		lblSoLuongHienThi.setForeground(new Color(64, 128, 128));
		lblSoLuongHienThi.setText("Hiển thị 0 sản phẩm!");
		lblSoLuongHienThi.setHorizontalAlignment(SwingConstants.CENTER);
		lblSoLuongHienThi.setFont(new Font("Segoe UI", Font.BOLD, 18));

		JLabel lblVND = new JLabel();
		lblVND.setToolTipText("");
		lblVND.setText("VNĐ");
		lblVND.setHorizontalAlignment(SwingConstants.LEFT);
		lblVND.setFont(new Font("Segoe UI", Font.PLAIN, 18));

		chckbxHetHangSach = new JCheckBox("");
		chckbxHetHangSach.addActionListener(this);
		lblHetHangSach = new JLabel("Hiện hết hàng:");
		lblHetHangSach.setFont(new Font("Segoe UI", Font.PLAIN, 18));

		javax.swing.GroupLayout pnlSachLayout = new javax.swing.GroupLayout(pnlSach);
		pnlSachLayout.setHorizontalGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlSachLayout
				.createSequentialGroup()
				.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlSachLayout
						.createSequentialGroup()
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(pnlSachLayout.createSequentialGroup().addGap(34)
										.addGroup(pnlSachLayout.createParallelGroup(Alignment.TRAILING)
												.addComponent(lblTenSach).addComponent(lblGiaNhapSach,
														GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)))
								.addComponent(lblMaSach, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 75,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtMaSach, GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
								.addComponent(txtTenSach)
								.addGroup(pnlSachLayout.createSequentialGroup()
										.addComponent(txtGiaSach, GroupLayout.PREFERRED_SIZE, 126,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(lblVND,
												GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)))
						.addGap(101)
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.TRAILING)
								.addGroup(pnlSachLayout.createSequentialGroup()
										.addComponent(lblTheLoaiSach, GroupLayout.PREFERRED_SIZE, 78,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED))
								.addComponent(lblTacGiaSach, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblSLSach))
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlSachLayout
								.createSequentialGroup()
								.addGroup(pnlSachLayout.createParallelGroup(Alignment.TRAILING).addGroup(pnlSachLayout
										.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(txtSoLuongSach, GroupLayout.PREFERRED_SIZE, 60,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(lblDonViSach)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(txtDonViSach,
												GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
										.addGroup(pnlSachLayout.createSequentialGroup()
												.addComponent(cmbTacGia, 0, 243, Short.MAX_VALUE)
												.addPreferredGap(ComponentPlacement.RELATED)))
								.addGap(71))
								.addComponent(cmbLoaiSach, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))
						.addGap(37)
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.TRAILING)
								.addComponent(lblNSXSach, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNCCSach, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(pnlSachLayout.createSequentialGroup().addComponent(lblHetHangSach)
										.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(chckbxHetHangSach))
								.addComponent(cmbNXB, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE)
								.addComponent(cmbNCCSach, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))
						.addGap(385))
						.addGroup(pnlSachLayout.createSequentialGroup().addContainerGap().addComponent(scrSach,
								GroupLayout.PREFERRED_SIZE, 1519, GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlSachLayout.createSequentialGroup().addGap(589).addComponent(lblSoLuongHienThi,
								GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlSachLayout.createSequentialGroup().addContainerGap().addComponent(jPanel14,
								GroupLayout.PREFERRED_SIZE, 1497, GroupLayout.PREFERRED_SIZE)))
				.addContainerGap()));
		pnlSachLayout.setVerticalGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlSachLayout
				.createSequentialGroup().addGap(18)
				.addGroup(pnlSachLayout.createParallelGroup(Alignment.TRAILING)
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txtMaSach, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblTacGiaSach).addComponent(lblMaSach)
								.addComponent(cmbTacGia, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
						.addComponent(
								lblNSXSach)
						.addComponent(cmbNXB, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
				.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlSachLayout
						.createSequentialGroup()
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING)
										.addGroup(pnlSachLayout.createSequentialGroup().addGap(20)
												.addGroup(pnlSachLayout.createParallelGroup(Alignment.BASELINE)
														.addComponent(lblTenSach)
														.addComponent(txtTenSach, GroupLayout.PREFERRED_SIZE, 30,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(lblNCCSach)))
										.addGroup(pnlSachLayout.createSequentialGroup()
												.addPreferredGap(ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
												.addComponent(lblTheLoaiSach).addGap(4)))
								.addGroup(pnlSachLayout.createSequentialGroup().addGap(18)
										.addComponent(cmbLoaiSach, GroupLayout.PREFERRED_SIZE, 27,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)))
						.addGroup(pnlSachLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(pnlSachLayout.createSequentialGroup().addGap(20)
										.addGroup(pnlSachLayout.createParallelGroup(Alignment.BASELINE)
												.addComponent(lblGiaNhapSach).addComponent(lblSLSach)
												.addComponent(txtGiaSach, GroupLayout.PREFERRED_SIZE, 30,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(txtSoLuongSach, GroupLayout.PREFERRED_SIZE, 30,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(lblDonViSach).addComponent(lblVND,
														GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)))
								.addGroup(pnlSachLayout.createSequentialGroup().addGap(18).addGroup(pnlSachLayout
										.createParallelGroup(Alignment.LEADING).addComponent(chckbxHetHangSach)
										.addGroup(pnlSachLayout.createParallelGroup(Alignment.BASELINE)
												.addComponent(txtDonViSach, GroupLayout.PREFERRED_SIZE, 30,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(lblHetHangSach)))))
						.addGap(18))
						.addGroup(pnlSachLayout.createSequentialGroup().addGap(18).addComponent(cmbNCCSach,
								GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.RELATED)
				.addComponent(scrSach, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE).addGap(18)
				.addComponent(lblSoLuongHienThi, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
				.addGap(28)));
		pnlSach.setLayout(pnlSachLayout);

		lblMaSach.getAccessibleContext().setAccessibleName("Mã Sách:");

		tbp_sanpham.addTab("Sách", null, pnlSach, "");

		lblMaVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMaVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblMaVPP.setText("Mã VPP:");

		lblTenVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTenVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblTenVPP.setText("Tên VPP:");

		lblMauVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMauVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblMauVPP.setText("Màu sắc:");

		lblGiaNhapVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblGiaNhapVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblGiaNhapVPP.setText("Giá nhập:");
		lblGiaNhapVPP.setToolTipText("");

		lblSL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblSL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblSL.setText("Số lượng:");

		lblDonViVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblDonViVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblDonViVPP.setText("Đơn vị:");

		txtDonViVPP.addActionListener(this);

		txtSoLuongVPP.addActionListener(this);

		lblNCCVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNCCVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNCCVPP.setText("NCC:");
		// Table VPP:
		String header_VPP[] = { "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Màu Sắc", "Số lượng", "Đơn vị", "Giá Nhập",
				"Loại sản phẩm", "Nhà cung cấp", "Nhà sản xuất" };
		tableModel_VPP = new DefaultTableModel(header_VPP, 0);
		tblVPP = new JTable(tableModel_VPP);
		tblVPP.addMouseListener(this);
		TableColumnModel columnMode = tblVPP.getColumnModel();
		columnMode.getColumn(0).setMaxWidth(40);
		scrVPP.setViewportView(tblVPP);

		jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnThemVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnThemVPP.setText("Thêm");
		btnThemVPP.setToolTipText("");
		btnThemVPP.setPreferredSize(new java.awt.Dimension(60, 30));
		btnThemVPP.addActionListener(this);

		btnLamMoiVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnLamMoiVPP.setText("Làm mới");
		btnLamMoiVPP.setPreferredSize(new java.awt.Dimension(60, 30));
		btnLamMoiVPP.addActionListener(this);

		btnCapNhatVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnCapNhatVPP.setText("Cập nhật");
		btnCapNhatVPP.setActionCommand("Sửa");
		btnCapNhatVPP.addActionListener(this);

		btnNhapVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnNhapVPP.setText("Nhập File");
		btnNhapVPP.addActionListener(this);

		btnXuatVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnXuatVPP.setText("Xuất File");
		btnXuatVPP.addActionListener(this);

		btnLuuVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnLuuVPP.setText("Lưu");
		btnLuuVPP.addActionListener(this);

		btnDanhMucVPP = new JButton();
		btnDanhMucVPP.setText("Quản lý danh mục");
		btnDanhMucVPP.setFont(new Font("Segoe UI", Font.PLAIN, 18));
		btnDanhMucVPP.addActionListener(this);
		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
		jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel13Layout
				.createSequentialGroup().addGap(27)
				.addComponent(btnLamMoiVPP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(54)
				.addComponent(btnThemVPP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(42)
				.addComponent(btnCapNhatVPP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(34)
				.addComponent(btnDanhMucVPP, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE).addGap(45)
				.addComponent(btnNhapVPP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(45)
				.addComponent(btnXuatVPP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE).addGap(36)
				.addComponent(btnLuuVPP, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
				.addContainerGap(163, Short.MAX_VALUE)));
		jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel13Layout.createSequentialGroup().addGap(17)
						.addGroup(jPanel13Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(btnThemVPP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLamMoiVPP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnDanhMucVPP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCapNhatVPP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnNhapVPP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXuatVPP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLuuVPP, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
						.addGap(20)));
		jPanel13.setLayout(jPanel13Layout);

		lblNSXVPP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblNSXVPP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNSXVPP.setText("NSX:");

		// Nhà cung cấp VPP:
		nhaCungCapVPPs = new ArrayList<NhaCungCap>();
		try {
			nhaCungCapVPPs = nhaCungCapServiceImpl.getListNhaCungCap("VPP");
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbNCCVPP = new JComboBox<Object>();
		cmbNCCVPP.addItem("");
		for (NhaCungCap nhaCungCap : nhaCungCaps) {
			cmbNCCVPP.addItem(nhaCungCap.getTenNhaCungCap());
		}
		// Nhà sản xuất:
		nhaSanXuats = new ArrayList<NhaSanXuat>();
		try {
			nhaSanXuats = nhaSanXuatServiceImpl.getListNhaSanXuat();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbNSX = new JComboBox<Object>();
		cmbNSX.addItem("");
		for (NhaSanXuat nhaSanXuat : nhaSanXuats) {
			cmbNSX.addItem(nhaSanXuat.getTenNhaSX());
		}
		// Màu Sắc
		mauSacs = new ArrayList<MauSac>();
		try {
			mauSacs = mauSacServiceImpl.getListMauSac();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		cmbMauSac = new JComboBox<Object>();
		cmbMauSac.addItem("");
		for (MauSac mauSac : mauSacs) {
			cmbMauSac.addItem(mauSac.getTenMau());
		}

		JLabel lblLoaiVPP = new JLabel();
		lblLoaiVPP.setText("Loại VPP");
		lblLoaiVPP.setHorizontalAlignment(SwingConstants.RIGHT);
		lblLoaiVPP.setFont(new Font("Segoe UI", Font.PLAIN, 18));
		// Thể loại VPP:
		theLoaiVanPhongPhams = new ArrayList<TheLoaiVanPhongPham>();
		try {
			theLoaiVanPhongPhams = theLoaiServiceImpl.getListTheLoaiVanPhongPham();
		} catch (Exception e1) {
			// TODO: handle exception
			e1.printStackTrace();
		}
		cmbLoaiVPP = new JComboBox<Object>();
		cmbLoaiVPP.addItem("");
		for (TheLoaiVanPhongPham theLoaiVanPhongPham : theLoaiVanPhongPhams) {
			cmbLoaiVPP.addItem(theLoaiVanPhongPham.getTenLoai());
		}

		lblVNDVPP = new JLabel();
		lblVNDVPP.setToolTipText("");
		lblVNDVPP.setText("VNĐ");
		lblVNDVPP.setHorizontalAlignment(SwingConstants.LEFT);
		lblVNDVPP.setFont(new Font("Segoe UI", Font.PLAIN, 18));

		lblHetHangVPP = new JLabel();
		lblHetHangVPP.setText("Hiện hết hàng:");
		lblHetHangVPP.setHorizontalAlignment(SwingConstants.RIGHT);
		lblHetHangVPP.setFont(new Font("Segoe UI", Font.PLAIN, 18));

		chckbxHetHangVPP = new JCheckBox("");
		chckbxHetHangVPP.addActionListener(this);
		lblSoLuongHienThiVPP = new JLabel("Hiển thị 0 sản phẩm");
		lblSoLuongHienThiVPP.setForeground(new Color(64, 128, 128));
		lblSoLuongHienThiVPP.setFont(new Font("Segoe UI", Font.BOLD, 18));
		javax.swing.GroupLayout pnlVPPLayout = new javax.swing.GroupLayout(pnlVPP);
		pnlVPPLayout.setHorizontalGroup(pnlVPPLayout.createParallelGroup(Alignment.TRAILING).addGroup(pnlVPPLayout
				.createSequentialGroup()
				.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlVPPLayout
						.createSequentialGroup().addGap(25)
						.addGroup(
								pnlVPPLayout.createParallelGroup(Alignment.TRAILING).addComponent(lblTenVPP)
										.addComponent(lblGiaNhapVPP, GroupLayout.PREFERRED_SIZE, 81,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lblMaVPP, GroupLayout.PREFERRED_SIZE, 75,
												GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtMaVPP, GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
								.addComponent(txtTenVPP)
								.addGroup(pnlVPPLayout.createSequentialGroup()
										.addComponent(txtGiaNhapVPP, GroupLayout.PREFERRED_SIZE, 135,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(lblVNDVPP,
												GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)))
						.addGap(116)
						.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING).addGroup(pnlVPPLayout
								.createSequentialGroup()
								.addGroup(pnlVPPLayout.createParallelGroup(Alignment.TRAILING)
										.addComponent(lblMauVPP, GroupLayout.PREFERRED_SIZE, 78,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lblSL))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING)
										.addGroup(pnlVPPLayout.createSequentialGroup()
												.addComponent(txtSoLuongVPP, GroupLayout.PREFERRED_SIZE, 60,
														GroupLayout.PREFERRED_SIZE)
												.addGap(18).addComponent(lblDonViVPP)
												.addPreferredGap(ComponentPlacement.RELATED).addComponent(txtDonViVPP,
														GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
										.addComponent(cmbMauSac, GroupLayout.PREFERRED_SIZE, 243,
												GroupLayout.PREFERRED_SIZE)))
								.addGroup(pnlVPPLayout.createSequentialGroup().addGap(1)
										.addComponent(lblNCCVPP, GroupLayout.PREFERRED_SIZE, 78,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(cmbNCCVPP,
												GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE)))
						.addGap(70)
						.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(pnlVPPLayout.createSequentialGroup()
										.addComponent(lblNSXVPP, GroupLayout.PREFERRED_SIZE, 78,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(cmbNSX,
												GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlVPPLayout.createSequentialGroup()
										.addComponent(lblLoaiVPP, GroupLayout.PREFERRED_SIZE, 78,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING)
												.addGroup(pnlVPPLayout.createSequentialGroup()
														.addComponent(lblHetHangVPP, GroupLayout.PREFERRED_SIZE, 132,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.UNRELATED)
														.addComponent(chckbxHetHangVPP))
												.addComponent(cmbLoaiVPP, GroupLayout.PREFERRED_SIZE, 243,
														GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(ComponentPlacement.RELATED, 316, Short.MAX_VALUE))
						.addGroup(pnlVPPLayout.createSequentialGroup().addContainerGap().addComponent(jPanel13,
								GroupLayout.DEFAULT_SIZE, 1509, Short.MAX_VALUE))
						.addGroup(pnlVPPLayout.createSequentialGroup().addContainerGap().addComponent(scrVPP,
								GroupLayout.PREFERRED_SIZE, 1509, GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlVPPLayout.createSequentialGroup().addGap(688).addComponent(lblSoLuongHienThiVPP)))
				.addContainerGap()));
		pnlVPPLayout.setVerticalGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(pnlVPPLayout.createSequentialGroup().addGap(18).addGroup(pnlVPPLayout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(pnlVPPLayout.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(pnlVPPLayout.createParallelGroup(Alignment.BASELINE)
										.addComponent(txtMaVPP, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
										.addComponent(lblMauVPP).addComponent(lblMaVPP))
								.addComponent(lblNSXVPP))
						.addComponent(cmbMauSac, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
						.addComponent(cmbNSX, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)).addGap(
								20)
						.addGroup(
								pnlVPPLayout.createParallelGroup(Alignment.LEADING)
										.addGroup(pnlVPPLayout
												.createSequentialGroup().addGroup(pnlVPPLayout
														.createParallelGroup(Alignment.BASELINE).addComponent(lblTenVPP)
														.addComponent(txtTenVPP, GroupLayout.PREFERRED_SIZE, 30,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(lblNCCVPP).addComponent(
																cmbNCCVPP, GroupLayout.PREFERRED_SIZE, 27,
																GroupLayout.PREFERRED_SIZE))
												.addGroup(pnlVPPLayout.createParallelGroup(Alignment.LEADING)
														.addGroup(pnlVPPLayout.createSequentialGroup().addGap(20)
																.addGroup(pnlVPPLayout
																		.createParallelGroup(Alignment.BASELINE)
																		.addComponent(lblGiaNhapVPP).addComponent(lblSL)
																		.addComponent(txtGiaNhapVPP,
																				GroupLayout.PREFERRED_SIZE, 30,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(txtSoLuongVPP,
																				GroupLayout.PREFERRED_SIZE, 30,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				lblDonViVPP)
																		.addComponent(lblVNDVPP,
																				GroupLayout.PREFERRED_SIZE, 25,
																				GroupLayout.PREFERRED_SIZE)))
														.addGroup(pnlVPPLayout.createSequentialGroup().addGap(18)
																.addGroup(pnlVPPLayout
																		.createParallelGroup(Alignment.LEADING)
																		.addComponent(chckbxHetHangVPP)
																		.addGroup(pnlVPPLayout
																				.createParallelGroup(Alignment.BASELINE)
																				.addComponent(txtDonViVPP,
																						GroupLayout.PREFERRED_SIZE, 30,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(lblHetHangVPP,
																						GroupLayout.PREFERRED_SIZE, 25,
																						GroupLayout.PREFERRED_SIZE))))))
										.addGroup(pnlVPPLayout.createParallelGroup(Alignment.TRAILING)
												.addComponent(lblLoaiVPP, GroupLayout.PREFERRED_SIZE, 25,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(cmbLoaiVPP, GroupLayout.PREFERRED_SIZE, 27,
														GroupLayout.PREFERRED_SIZE)))
						.addComponent(jPanel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(scrVPP, GroupLayout.PREFERRED_SIZE, 372, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(lblSoLuongHienThiVPP).addGap(379)));
		pnlVPP.setLayout(pnlVPPLayout);

		tbp_sanpham.addTab("Văn Phòng Phẩm", null, pnlVPP, "");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(tbp_sanpham, GroupLayout.PREFERRED_SIZE, 1523, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(102, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(tbp_sanpham, GroupLayout.PREFERRED_SIZE, 696, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(lblLapPhieuDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1540,
										Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap())));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
						.addComponent(lblLapPhieuDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(1103, Short.MAX_VALUE))
				.addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(125, 125, 125)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap())));
		try {
			loadDuLieuSach();
			loadDuLieuVPP();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCapNhatSP;
	private javax.swing.JButton btnCapNhatSach;
	private javax.swing.JButton btnCapNhatVPP;
	private javax.swing.JButton btnLamMoiSP;
	private javax.swing.JButton btnLamMoiSach;
	private javax.swing.JButton btnLamMoiVPP;
	private javax.swing.JButton btnLuuSach;
	private javax.swing.JButton btnLuuVPP;
	private javax.swing.JButton btnNhapSP;
	private javax.swing.JButton btnNhapSach;
	private javax.swing.JButton btnNhapVPP;
	private javax.swing.JButton btnThemSP;
	private javax.swing.JButton btnThemSach;
	private javax.swing.JButton btnThemVPP;
	private javax.swing.JButton btnThemVpp5;
	private javax.swing.JButton btnDanhMucSach;
	private javax.swing.JButton btnXuatSP;
	private javax.swing.JButton btnXuatSach;
	private javax.swing.JButton btnXuatVPP;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JScrollPane scrTatca;
	private javax.swing.JScrollPane scrVPP;
	private javax.swing.JScrollPane scrSach;
	private javax.swing.JTable tblTatCa;
	private javax.swing.JTextField jTextField26;
	private javax.swing.JTextField jTextField27;
	private javax.swing.JLabel lblDonViSP;
	private javax.swing.JLabel lblDonViSach;
	private javax.swing.JLabel lblDonViVPP;
	private javax.swing.JLabel lblGiaNhapSP;
	private javax.swing.JLabel lblGiaNhapSach;
	private javax.swing.JLabel lblGiaNhapVPP;
	private javax.swing.JLabel lblLapPhieuDatHang;
	private javax.swing.JLabel lblMaSP;
	private javax.swing.JLabel lblMaSach;
	private javax.swing.JLabel lblMaVPP;
	private javax.swing.JLabel lblMauSP;
	private javax.swing.JLabel lblMauVPP;
	private javax.swing.JLabel lblNCCSP;
	private javax.swing.JLabel lblNCCSach;
	private javax.swing.JLabel lblNCCVPP;
	private javax.swing.JLabel lblNSXSP;
	private javax.swing.JLabel lblNSXSach;
	private javax.swing.JLabel lblNSXVPP;
	private javax.swing.JLabel lblNXBSP;
	private javax.swing.JLabel lblSL;
	private javax.swing.JLabel lblSLSP;
	private javax.swing.JLabel lblSLSach;
	private javax.swing.JLabel lblTacGiaSP;
	private javax.swing.JLabel lblTacGiaSach;
	private javax.swing.JLabel lblTenSP;
	private javax.swing.JLabel lblTenSach;
	private javax.swing.JLabel lblTenVPP;
	private javax.swing.JLabel lblTheLoaiSach;
	public javax.swing.JPanel pnlSach;
	public javax.swing.JPanel pnlTatCa;
	public javax.swing.JPanel pnlVPP;
	private javax.swing.JTable tblSach;
	private javax.swing.JTable tblVPP;
	private javax.swing.JTabbedPane tbp_sanpham;
	private javax.swing.JTextField txtDonViSach;
	private javax.swing.JTextField txtDonViVPP;
	private javax.swing.JTextField txtGiaNhapSP;
	private javax.swing.JTextField txtGiaNhapVPP;
	private javax.swing.JTextField txtGiaSach;
	private javax.swing.JTextField txtMaSP;
	private javax.swing.JTextField txtMaSach;
	private javax.swing.JTextField txtMaVPP;
	private javax.swing.JTextField txtMauSP;
	private javax.swing.JTextField txtNCCSP;
	private javax.swing.JTextField txtNSXSP;
	private javax.swing.JTextField txtNXBSP;
	private javax.swing.JTextField txtSoLuongVPP;
	private javax.swing.JTextField txtSoLuongSach;
	private javax.swing.JTextField txtTacGiaSP;
	private javax.swing.JTextField txtTenSach;
	private javax.swing.JTextField txtTenSp;
	private javax.swing.JTextField txtTenVPP;
	private List<Sach> listSach;
	private List<VanPhongPham> listVPP;
	private ArrayList<TacGia> tacGias;
	private ArrayList<NhaXuatBan> nhaXuatBans;
	private ArrayList<NhaCungCap> nhaCungCaps;
	private ArrayList<NhaSanXuat> nhaSanXuats;
	private DefaultTableModel tableModel_SanPham;
	private DefaultTableModel tableModel_Sach;
	private DefaultTableModel tableModel_VPP;
	private JComboBox<Object> cmbNCCSach;
	private JComboBox<Object> cmbNCCVPP;
	private JComboBox<Object> cmbNSX;
	private JComboBox<Object> cmbNXB;
	private JComboBox<Object> cmbTacGia;
	private JComboBox<Object> cmbMauSac;
	private ArrayList<MauSac> mauSacs;
	SanPhamServiceImpl sanPhamServiceImpl = new SanPhamServiceImpl();
	TacGiaServiceImpl tacGiaServiceImpl = new service_impl.TacGiaServiceImpl();
	NhaSanXuatServiceImpl nhaSanXuatServiceImpl = new NhaSanXuatServiceImpl();
	NhaCungCapServiceImpl nhaCungCapServiceImpl = new NhaCungCapServiceImpl();
	NhaXuatBanServiceImpl nhaXuatBanServiceImpl = new NhaXuatBanServiceImpl();
	private JComboBox<Object> cmbLoaiSach;
	private JLabel lblVNDVPP;
	private JLabel lblHetHangVPP;
	private JCheckBox chckbxHetHangSach;
	private JLabel lblHetHangSach;
	private JLabel lblSoLuongHienThiVPP;
	private final static int tenSach = 0;
	private final static int tenTacGia = 1;
	private final static int tenNhaXuatBan = 2;
	private final static int tenTheLoai = 3;
	private final static int soLuongTon = 4;
	private final static int tenNhaCungCap = 5;
	private final static int giaNhap = 6;
	private final static int giaBan = 7;
	
	private final static int tenVanPhongPham = 0;
	private final static int tenLoaiVanPhongPham = 1;
	private final static int tenMauSac = 2;
	private final static int tenNhaSanXuat = 3;
	private final static int soLuongTonvpp = 4;
	private final static int tenNhaCungCapvpp = 5;
	private final static int giaNhapvpp = 6;
	private final static int giaBanvpp = 7;
	private HSSFWorkbook hssfWorkbook;
	private JFileChooser filechoose;
	private File file;

	// End of variables declaration//GEN-END:variables
	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if (o.equals(tblSach)) {
			int i = tblSach.getSelectedRow();
			setHienThiSach(i);
		}
		if (o.equals(tblVPP)) {
			int j = tblVPP.getSelectedRow();
			setHienThiVPP(j);
		}

	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object src = e.getSource();
		
		if (src.equals(chckbxHetHangSach)) {
			try {
				this.loadDuLieuSach();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		
		if (src.equals(chckbxHetHangVPP)) {
			try {
				this.loadDuLieuVPP();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		
		if (src.equals(btnLamMoiSach) || src.equals(btnLamMoiVPP)) {
			this.lamMoiSach();
			this.lamMoiVPP();
			try {
				this.loadDuLieuSach();
				this.loadDuLieuVPP();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		if (src.equals(btnThemSach)) {
			lamMoiVPP();
			this.themSP();
		}
		if (src.equals(btnThemVPP)) {
			lamMoiSach();
			this.themSP();
		}
		if (src.equals(btnCapNhatSach)) {
			lamMoiVPP();
			int row = tblSach.getSelectedRow();
			if (row == -1) {
				JOptionPane.showMessageDialog(null, "Chưa chọn dòng nào!!", "Thông báo",
						JOptionPane.INFORMATION_MESSAGE);
			} else {
				String maSP = tableModel_Sach.getValueAt(row, 0).toString();
				String loai = "Sách";
				this.capNhatSP(maSP, loai);

			}
			try {
				lamMoiSach();
				loadDuLieuSach();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}

		}
		if (src.equals(btnCapNhatVPP)) {
			lamMoiSach();
			int row = tblVPP.getSelectedRow();
			if (row == -1) {
				JOptionPane.showMessageDialog(null, "Chưa chọn dòng nào!!", "Thông báo",
						JOptionPane.INFORMATION_MESSAGE);
			} else {
				String maSP = tableModel_VPP.getValueAt(row, 0).toString();
				String loai = "VPP";
				this.capNhatSP(maSP, loai);

			}
			try {
				lamMoiVPP();
				loadDuLieuVPP();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		if (src.equals(btnDanhMucSach)) {
			new Frm_QuanLyDanhMuc("Sách").setVisible(true);
		}
		if (src.equals(btnDanhMucVPP)) {
			new Frm_QuanLyDanhMuc("Văn phòng phẩm").setVisible(true);
		}
		if (src.equals(btnXuatSach)) {
			filechoose = new JFileChooser();
			FileNameExtensionFilter filter = new FileNameExtensionFilter("*.xlsx", "xlsx");
			filechoose.setFileFilter(filter);
			filechoose.setMultiSelectionEnabled(false);

			String filePath = "";
			int x = filechoose.showDialog(this, "Chọn File");
			if (x == JFileChooser.APPROVE_OPTION) {
				file = filechoose.getSelectedFile();
				filePath = file.getAbsolutePath();
				if (!filePath.endsWith(".xlsx")) {
					filePath += ".xlsx";
				}
			}
			if (filePath.equals("")) {
				return;
			}
			listSach = new ArrayList<Sach>();
			int row = tblSach.getRowCount();
			System.out.println(row);
			for (int i = 0; i < row; i++) {
				try {
					Sach s = sanPhamServiceImpl.timSanPhamTheoMaSach(tableModel_Sach.getValueAt(i, 1).toString());
					listSach.add(s);
					s.toString();
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}

			try {
				exportSach(listSach, filePath);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			if (JOptionPane.showConfirmDialog(null, "Export thành công!!\nBạn có muốn mở file?", "Thông báo",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
				Desktop desktop = Desktop.getDesktop();
				File file = new File(filePath);
				if (file.exists())
					try {
						desktop.open(file);
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
			}
		}
		if (src.equals(btnXuatVPP)) {
			filechoose = new JFileChooser();
			FileNameExtensionFilter filter = new FileNameExtensionFilter("*.xlsx", "xlsx");
			filechoose.setFileFilter(filter);
			filechoose.setMultiSelectionEnabled(false);

			String filePath = "";
			int x = filechoose.showDialog(this, "Chọn File");
			if (x == JFileChooser.APPROVE_OPTION) {
				file = filechoose.getSelectedFile();
				filePath = file.getAbsolutePath();
				if (!filePath.endsWith(".xlsx")) {
					filePath += ".xlsx";
				}
			}
			if (filePath.equals("")) {
				return;
			}
			ArrayList<VanPhongPham> listVPP = new ArrayList<>();
			int row = tblVPP.getRowCount();
			for (int i = 0; i < row; i++) {
				try {
					VanPhongPham vpp = sanPhamServiceImpl
							.timSanPhamTheoMaVPP(tableModel_VPP.getValueAt(i, 1).toString());
					listVPP.add(vpp);
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}

			try {
				exportVPP(listVPP, filePath);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			if (JOptionPane.showConfirmDialog(null, "Export thành công!!\nBạn có muốn mở file?", "Thông báo",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
				Desktop desktop = Desktop.getDesktop();
				File file = new File(filePath);
				if (file.exists())
					try {
						desktop.open(file);
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
			}
		}
		
		if (src.equals(btnNhapSach)) {
			filechoose = new JFileChooser("../QLHS/sql");
			filechoose.setMultiSelectionEnabled(false);
			String filePath = "";
			int x = filechoose.showDialog(this, "Chọn File");
			if (x == JFileChooser.APPROVE_OPTION) {
				file = filechoose.getSelectedFile();
				filePath = file.getAbsolutePath();
			}
			if (!filePath.endsWith(".xlsx")) {
				return;
			}
				int count = 0;
				try {
					count = importSach(filePath);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				String s = "Import thành công " + count + " cuốn sách!!";
				JOptionPane.showMessageDialog(null, s, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
				lamMoiSach();
		}
		
		if (src.equals(btnNhapVPP)) {
			filechoose = new JFileChooser("../QLHS/sql");
			filechoose.setMultiSelectionEnabled(false);
			String filePath = "";
			int x = filechoose.showDialog(this, "Chọn File");
			if (x == JFileChooser.APPROVE_OPTION) {
				file = filechoose.getSelectedFile();
				filePath = file.getAbsolutePath();
			}
			if (!filePath.endsWith(".xlsx")) {
				return;
			}
			int count = 0;
			try {
				count = importVPP(filePath);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			String s = "Import thành công " + count + " văn phòng phẩm!!";
			JOptionPane.showMessageDialog(null, s, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
			lamMoiVPP();
		}
		
	}

	public void lamMoiSach() {
		txtDonViSach.setText("");
		try {
			txtMaSach.setText(tangMaSP());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		txtGiaSach.setText("");
		cmbNCCSach.setSelectedIndex(0);
		cmbTacGia.setSelectedIndex(0);
		cmbNXB.setSelectedIndex(0);
		cmbLoaiSach.setSelectedIndex(0);
		txtTenSach.setText("");
		txtSoLuongSach.setText("");
	}

	public void lamMoiVPP() {
		txtDonViVPP.setText("");
		try {
			txtMaVPP.setText(tangMaSP());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		txtGiaNhapVPP.setText("");
		cmbMauSac.setSelectedIndex(0);
		cmbNCCVPP.setSelectedIndex(0);
		cmbNSX.setSelectedIndex(0);
		cmbLoaiVPP.setSelectedIndex(0);
		txtTenVPP.setText("");
		txtSoLuongVPP.setText("");
	}

	public void capNhatSP(String maSanPham, String loaiSanPham) {
		Sach s = new Sach();
		VanPhongPham v = new VanPhongPham();
		if (loaiSanPham.equals("Sách")) {
			s = taoSach();
			if (s == null) {
				return;
			}
			try {
				boolean kt = sanPhamServiceImpl.capNhatSanPham(s.getMaSanPham(), s);
				if (kt == true) {
					JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
				} else {
					JOptionPane.showMessageDialog(null,
							"Số trang phải lớn hơn 0!\nSố lượng phải lớn hơn 0!\nTrọng lượng phải lớn hơn 0!\n Giá nhập lớn hơn 1000!",
							"Báo lỗi", JOptionPane.ERROR_MESSAGE);
				}
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		} else {
			v = taoVanPhongPham();
			if (v == null)
				return;
			try {
				boolean kt = sanPhamServiceImpl.capNhatSanPham(v.getMaSanPham(), v);
				if (kt == true) {
					JOptionPane.showMessageDialog(null, "Cập nhật thành công !!!");
				} else {
					JOptionPane.showMessageDialog(null,
							"Số lượng phải lớn hơn 0!\nTrọng lượng phải lớn hơn 0!\n Giá nhập lớn hơn 1000!", "Báo lỗi",
							JOptionPane.ERROR_MESSAGE);
				}
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		}
	}

	public void themSP() {
		if (txtTenSach.getText().equals("") && txtTenVPP.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Tên sản phẩm không được để rỗng", "Báo lỗi",
					JOptionPane.ERROR_MESSAGE);
			txtTenSach.requestFocus();
			txtTenSach.selectAll();
			txtTenVPP.requestFocus();
			txtTenVPP.selectAll();
			return;
		}
		Sach s = new Sach();
		VanPhongPham v = new VanPhongPham();
		if (!txtTenSach.getText().equals("")) {
			s = taoSach();
			if (s == null) {
				return;
			}
			try {
				boolean kt = sanPhamServiceImpl.themSanPham(s);
				if (kt == true) {
					JOptionPane.showMessageDialog(null, "Thêm thành công !!!");
					tableModel_Sach.setRowCount(0);
					lamMoiSach();
					loadDuLieuSach();
					txtMaSach.setText(tangMaSP());
				} else {
					JOptionPane.showMessageDialog(null, "Sản phẩm đã tồn tại", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
					txtTenSp.requestFocus();
					txtTenSp.selectAll();
				}
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		} else {
			try {
				v = taoVanPhongPham();
				if (v == null) {
					return;
				}
				boolean kt = sanPhamServiceImpl.themSanPham(v);
				if (kt == true) {
					JOptionPane.showMessageDialog(null, "Thêm thành công !!!");
					tableModel_VPP.setRowCount(0);
					lamMoiVPP();
					loadDuLieuVPP();
					txtMaVPP.setText(tangMaSP());
				} else {
					JOptionPane.showMessageDialog(null, "Sản phẩm đã tồn tại", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
					txtTenSp.requestFocus();
					txtTenSp.selectAll();
				}
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
	}

	public String tangMaSP() throws SQLException {
		String s = sanPhamServiceImpl.getMaSPMax();
		String so = s.substring(2).replaceAll("\\s+", "");
		int n = Integer.parseInt(so);
		if ((n + 1) % 10 == 0) {
			s = s.replaceAll("0" + n + "", n + 1 + "");
		} else
			s = s.replaceAll(n + "", n + 1 + "");
		return s;
	}

	public VanPhongPham taoVanPhongPham() {
		VanPhongPham v = null;
		String maSanPham = txtMaVPP.getText().toString().trim();
		String loaiSanPham = "VPP";
		int soLuongTon;
		try {
			soLuongTon = Integer.parseInt(txtSoLuongVPP.getText().trim());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Số lượng không được là chữ!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
			txtSoLuongVPP.requestFocus();
			txtSoLuongVPP.selectAll();
			return null;
		}
		if (soLuongTon < 0 || soLuongTon > 10000) {
			JOptionPane.showMessageDialog(null, "Số lượng lớn hơn 0 và bé hơn 10000", "Báo lỗi",
					JOptionPane.ERROR_MESSAGE);
			txtSoLuongVPP.requestFocus();
			txtSoLuongVPP.selectAll();
			return null;
		}
		NhaCungCap nhaCungCap = nhaCungCaps.get(cmbNCCVPP.getSelectedIndex() - 1);
		long giaNhap;
		try {
			giaNhap = Long.parseLong(txtGiaNhapVPP.getText().trim());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Giá nhập không được là chữ!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
			txtGiaNhapVPP.requestFocus();
			txtGiaNhapVPP.selectAll();
			return null;
		}
		long giaBan = (giaNhap * 20 / 100) + giaNhap;
		String donViSanPham = txtDonViVPP.getText();
		String tenVPP = txtTenVPP.getText().trim();
		MauSac mauSac = mauSacs.get(cmbMauSac.getSelectedIndex() - 1);
		NhaSanXuat nhaSanXuat = nhaSanXuats.get(cmbNSX.getSelectedIndex() - 1);
		TheLoaiVanPhongPham loaiVanPhongPham = theLoaiVanPhongPhams.get(cmbLoaiVPP.getSelectedIndex() - 1);
		v = new VanPhongPham(maSanPham, nhaCungCap, loaiSanPham, soLuongTon, donViSanPham, giaNhap, giaBan, tenVPP,
				mauSac, nhaSanXuat, loaiVanPhongPham);
		return v;
	}

	private Sach taoSach() {
		Sach s = null;
		String maSanPham = txtMaSach.getText().toString().trim();
		String loaiSanPham = "Sách";
		int soLuongTon;
		try {
			soLuongTon = Integer.parseInt(txtSoLuongSach.getText().trim());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Số lượng không được là chữ!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
			txtSoLuongSach.requestFocus();
			txtSoLuongSach.selectAll();
			return null;
		}
		if (soLuongTon < 0 || soLuongTon >= 10000) {
			JOptionPane.showMessageDialog(null, "Số lượng >= 0 và < 10000!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
			txtSoLuongSach.requestFocus();
			txtSoLuongSach.selectAll();
			return null;
		}

		long giaNhap;
		try {
			giaNhap = Long.parseLong(txtGiaSach.getText().trim());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Giá nhập không được là chữ!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
			txtGiaSach.requestFocus();
			txtGiaSach.selectAll();
			return null;
		}
		if (giaNhap < 1000 || giaNhap >= 10000000) {
			JOptionPane.showMessageDialog(null, "Giá nhập lớn hơn 1000 và bé hơn 10000000!!", "Báo lỗi",
					JOptionPane.ERROR_MESSAGE);
			txtGiaSach.requestFocus();
			txtGiaSach.selectAll();
			return null;
		}
		String donVi = txtDonViSach.getText();
		String tenSach = txtTenSach.getText().trim();
		TacGia tacGia = tacGias.get(cmbTacGia.getSelectedIndex() - 1);
		NhaXuatBan nhaXuatBan = nhaXuatBans.get(cmbNXB.getSelectedIndex() - 1);
		NhaCungCap nhaCungCap = nhaCungCaps.get(cmbNCCSach.getSelectedIndex() - 1);

		long giaBan = (giaNhap * 20 / 100) + giaNhap;
		TheLoaiSach theLoaiSach = theLoaiSachs.get(cmbLoaiSach.getSelectedIndex() - 1);
		s = new Sach(maSanPham, nhaCungCap, loaiSanPham, soLuongTon, donVi, giaNhap, giaBan, tenSach, tacGia,
				nhaXuatBan, theLoaiSach);
		return s;
	}

	public void loadSanPham() throws Exception {
		SanPhamServiceImpl sanPhamService = new SanPhamServiceImpl();
		listSach = sanPhamService.getAllSach();
		listVPP = sanPhamService.getAllVPP();
		String header_SanPham[] = { "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn vị", "Giá nhập", "Giá bán",
				"Nhà cung cấp", "Tác giả", "Nhà xuất bản" };
		int i = 0;// Sach(maSanPham, ncc, loaiSP, soLuongTon, donVi,
					// giaNhap,giaBan,tenSach,tacGia,nhaXuatBan,theLoai )
		for (Sach sp : listSach) {
			Object ob[] = { i++ + "", sp.getMaSanPham(), sp.getTenSach(), sp.getSoLuongTon() + "", sp.getDonVi(),
					sp.getGiaNhap() + "", sp.getLoaiSanPham() + "", sp.getNhaCungCap().getMaNhaCungCap(),
					sp.getTacGia().getTenTacGia(), sp.getNhaXuatBan().getTenNXB() };
			tableModel_SanPham.addRow(ob);
		}

		for (VanPhongPham vpp : listVPP) {
			Object obj[] = { i++ + "", vpp.getMaSanPham(), vpp.getTenVanPhongPham(), vpp.getSoLuongTon() + "",
					vpp.getDonVi(), vpp.getGiaNhap() + "", vpp.getLoaiSanPham(), vpp.getNhaCungCap().getMaNhaCungCap(),
					vpp.getNhaSanXuat().getTenNhaSX(), vpp.getMauSac() };
			tableModel_SanPham.addRow(obj);
		}
	}

	public void loadDuLieuSach() throws Exception {
		listSach = new ArrayList<Sach>();
		String maSach = "";

		String tenSP = txtTenSach.getText().trim();

		String maTheLoai = "";
		if (cmbLoaiSach.getSelectedIndex() != 0) {
			maTheLoai = theLoaiSachs.get(cmbLoaiSach.getSelectedIndex() - 1).getMaLoai();
			System.out.println("Ma thể loại là: " + maTheLoai);
			// maTheLoai = theLoaiSachs.get(cmbLoaiSach.getSelectedIndex()-1).getMaLoai();
		}
		Long giaTu = (long) 0;
		Long giaDen = (long) 100000000;
//		if (cbbGia.getSelectedIndex() != 0) {
//			int key = cbbGia.getSelectedIndex();
//			switch (key) {
//			case 1:
//				giaTu = (long) 0;
//				giaDen = (long) 50001;
//				break;
//			case 2:
//				giaTu = (long) 50001;
//				giaDen = (long) 120001;
//				break;
//			case 3:
//				giaTu = (long) 120001;
//				giaDen = (long) 250001;
//				break;
//			case 4:
//				giaTu = (long) 250001;
//				giaDen = (long) 100000000;
//				break;
//			default:
//				break;
//			}
//		}
//		try {
//			if (!txtGiaTu.getText().trim().equals("Từ 0đ") && !txtGiaDen.getText().trim().equals("Đến 10,000,000đ")) {
//				giaTu = Long.parseLong(txtGiaTu.getText().trim());
//				giaDen = Long.parseLong(txtGiaDen.getText().trim());
//			}
//		} catch (Exception e) {
//			JOptionPane.showMessageDialog(null, "Giá từ bao nhiêu đến bao nhiêu phải nhập số!!!");
//			txtGiaTu.requestFocus();
//			return;
//		}

		String maTacGia = "";
		if (cmbTacGia.getSelectedIndex() != 0)
			maTacGia = tacGias.get(cmbTacGia.getSelectedIndex() - 1).getMaTacGia();
		String maNXB = "";
		if (cmbNSX.getSelectedIndex() != 0)
			maNXB = nhaXuatBans.get(cmbNSX.getSelectedIndex() - 1).getMaNXB();
		String maNCC = "";
		if (cmbNCCSach.getSelectedIndex() != 0)
			maNCC = nhaCungCaps.get(cmbNCCSach.getSelectedIndex() - 1).getMaNhaCungCap();

		try {
			listSach = sanPhamServiceImpl.getListSach(maSach, tenSP, maTheLoai, giaTu, giaDen, maTacGia, maNXB, maNCC,chckbxHetHangSach.isSelected());
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}

		tableModel_Sach.setRowCount(0);
//		if (listSach == null) {
//			JOptionPane.showMessageDialog(null, "Giá từ bao nhiêu phải bé hơn giá nhập!!", "Báo lỗi",
//					JOptionPane.ERROR_MESSAGE);
//			txtGiaTu.requestFocus();
//			txtGiaTu.selectAll();
//			return;
//		}
		int i = 0;
		for (Sach sp : listSach) {
			Object ob[] = { i += 1, sp.getMaSanPham(), sp.getTenSach(), sp.getSoLuongTon() + "", sp.getDonVi(),
					sp.getGiaNhap(), sp.getTheLoaiSach().getTenLoai() + "", sp.getNhaCungCap().getTenNhaCungCap(),
					sp.getTacGia().getTenTacGia(), sp.getNhaXuatBan().getTenNXB() };
			tableModel_Sach.addRow(ob);
		}
		lblSoLuongHienThi.setText("Hiển thị " + listSach.size() + " sản phẩm");
		TableColumnModel columnMode = tblSach.getColumnModel();
		columnMode.getColumn(0).setMaxWidth(40);
		columnMode.getColumn(1).setMaxWidth(150);
		columnMode.getColumn(3).setMaxWidth(60);
		columnMode.getColumn(4).setMaxWidth(60);
		columnMode.getColumn(5).setMaxWidth(150);
	}

	public void loadDuLieuVPP() {
		listVPP = new ArrayList<VanPhongPham>();
		String maVPP = "";
		String tenVPP = txtTenVPP.getText().trim();
		if (!tenVPP.equals(""))
			maVPP = txtMaVPP.getText().trim();
		String maTheLoai = "";
		if (cmbLoaiVPP.getSelectedIndex() != 0)
			maTheLoai = theLoaiVanPhongPhams.get(cmbLoaiVPP.getSelectedIndex() - 1).getMaLoai();
		Long giaTu = (long) 0;
		Long giaDen = (long) 100000000;
		String maNSX = "";
		if (cmbNSX.getSelectedIndex() != 0)
			maNSX = nhaSanXuats.get(cmbNSX.getSelectedIndex() - 1).getMaNhaSX();
		String maNCC = "";
		if (cmbNCCVPP.getSelectedIndex() != 0)
			maNCC = nhaCungCaps.get(cmbNCCVPP.getSelectedIndex() - 1).getMaNhaCungCap();
		try {
			listVPP = sanPhamServiceImpl.getListVanPhongPham(maVPP, tenVPP, maTheLoai, giaTu, giaDen, maNSX, maNCC,
					chckbxHetHangVPP.isSelected());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		tableModel_VPP.setRowCount(0);
		int i = 0;
		for (VanPhongPham vpp : listVPP) {
			Object obj[] = { i += 1, vpp.getMaSanPham(), vpp.getTenVanPhongPham(), vpp.getMauSac().getTenMau(),
					vpp.getSoLuongTon() + "", vpp.getDonVi(), vpp.getGiaNhap(), vpp.getLoaiVanPhongPham().getTenLoai(),
					vpp.getNhaCungCap().getTenNhaCungCap(), vpp.getNhaSanXuat().getTenNhaSX(), vpp.getMauSac() };
			tableModel_VPP.addRow(obj);
		}
		lblSoLuongHienThiVPP.setText("Hiển thị " + listVPP.size() + " sản phẩm");
		TableColumnModel columnMode = tblVPP.getColumnModel();
		columnMode.getColumn(0).setMaxWidth(40);
		columnMode.getColumn(1).setMaxWidth(150);
		columnMode.getColumn(3).setMaxWidth(100);
		columnMode.getColumn(4).setMaxWidth(60);
		columnMode.getColumn(5).setMaxWidth(80);
		columnMode.getColumn(6).setMaxWidth(120);
	}

	public void loadSach() throws Exception {
		SanPhamServiceImpl sanPhamService = new SanPhamServiceImpl();
		listSach = sanPhamService.getAllSach();
		int i = 1;
		for (Sach sp : listSach) {
			Object ob[] = { i++ + "", sp.getMaSanPham(), sp.getTenSach(), sp.getSoLuongTon() + "", sp.getDonVi(),
					sp.getGiaNhap() + " VNĐ", sp.getTheLoaiSach().getTenLoai() + "",
					sp.getNhaCungCap().getMaNhaCungCap(), sp.getTacGia().getTenTacGia(),
					sp.getNhaXuatBan().getTenNXB() };
			tableModel_Sach.addRow(ob);
		}
	}

	public void loadVPP() throws Exception {
		SanPhamServiceImpl sanPhamService = new SanPhamServiceImpl();
		listVPP = sanPhamService.getAllVPP();
		int i = 1;
		for (VanPhongPham vpp : listVPP) {
			Object obj[] = { i++ + "", vpp.getMaSanPham(), vpp.getTenVanPhongPham(), vpp.getMauSac().getTenMau(),
					vpp.getSoLuongTon() + "", vpp.getDonVi(), vpp.getGiaNhap() + " VNĐ", vpp.getLoaiSanPham() + "",
					vpp.getNhaCungCap().getMaNhaCungCap(), vpp.getNhaSanXuat().getTenNhaSX(), vpp.getMauSac() };
			tableModel_VPP.addRow(obj);
		}
	}

	public void setHienThiSach(int row) {
		txtMaSach.setText(tblSach.getValueAt(row, 1) + "");
		txtTenSach.setText(tblSach.getValueAt(row, 2) + "");
		txtGiaSach.setText(tblSach.getValueAt(row, 5).toString());
		txtSoLuongSach.setText(tblSach.getValueAt(row, 3) + "");
		txtDonViSach.setText(tblSach.getValueAt(row, 4) + "");
		cmbTacGia.setSelectedItem(tblSach.getValueAt(row, 8) + "");
		cmbLoaiSach.setSelectedItem(tblSach.getValueAt(row, 6) + "");
		cmbNCCSach.setSelectedItem(tblSach.getValueAt(row, 7) + "");
		cmbNXB.setSelectedItem(tblSach.getValueAt(row, 9) + "");
	}

	public void setHienThiVPP(int row) {
		txtMaVPP.setText(tblVPP.getValueAt(row, 1) + "");
		txtTenVPP.setText(tblVPP.getValueAt(row, 2) + "");
		cmbMauSac.setSelectedItem(tblVPP.getValueAt(row, 3) + "");
		txtSoLuongVPP.setText(tblVPP.getValueAt(row, 4) + "");
		txtDonViVPP.setText(tblVPP.getValueAt(row, 5) + "");
		txtGiaNhapVPP.setText(tblVPP.getValueAt(row, 6).toString());
		cmbLoaiVPP.setSelectedItem(tblVPP.getValueAt(row, 7) + "");
		cmbNCCVPP.setSelectedItem(tblVPP.getValueAt(row, 8) + "");
		cmbNSX.setSelectedItem(tblVPP.getValueAt(row, 9) + "");
	}

	public static void exportVPP(List<VanPhongPham> listVpp, String excelFilePath) throws IOException {
		// Create Workbook
		Workbook workbook = null;

		if (excelFilePath.endsWith("xlsx")) {
			workbook = new XSSFWorkbook();
		} else if (excelFilePath.endsWith("xls")) {
			workbook = new HSSFWorkbook();
		} else {
			throw new IllegalArgumentException("The specified file is not Excel file");
		}

		// Create sheet
		Sheet sheet = workbook.createSheet("VanPhongPham"); // Create sheet with sheet name

		int rowIndex = 0;

		// Write header
		Row row = sheet.createRow(rowIndex);
		// Create cells
		Cell cell = row.createCell(0);
		cell.setCellValue("Mã văn phòng phẩm");

		cell = row.createCell(tenVanPhongPham + 1);
		cell.setCellValue("Tên văn phòng phẩm");

		cell = row.createCell(tenLoaiVanPhongPham + 1);
		cell.setCellValue("Tên loại văn phòng phẩm");

		cell = row.createCell(tenMauSac + 1);
		cell.setCellValue("Màu sắc");

		cell = row.createCell(tenNhaSanXuat + 1);
		cell.setCellValue("Nhà sản xuất");

		cell = row.createCell(soLuongTonvpp + 1);
		cell.setCellValue("Số lượng");

		cell = row.createCell(tenNhaCungCapvpp + 1);
		cell.setCellValue("Nhà cung cấp");

		cell = row.createCell(giaNhapvpp + 1);
		cell.setCellValue("Giá nhập");

		cell = row.createCell(giaBanvpp + 1);
		cell.setCellValue("Giá bán");
		
		// Write data
		rowIndex++;
		for (VanPhongPham vanPhongPham : listVpp) {
			// Create row
			row = sheet.createRow(rowIndex);
			// Write data on row
			cell = row.createCell(0);
			cell.setCellValue(vanPhongPham.getMaSanPham());

			cell = row.createCell(tenVanPhongPham + 1);
			cell.setCellValue(vanPhongPham.getTenVanPhongPham());

			cell = row.createCell(tenLoaiVanPhongPham + 1);
			cell.setCellValue(vanPhongPham.getLoaiVanPhongPham().getTenLoai());

			cell = row.createCell(tenMauSac + 1);
			cell.setCellValue(vanPhongPham.getMauSac().getTenMau());

			cell = row.createCell(soLuongTonvpp + 1);
			cell.setCellValue(vanPhongPham.getSoLuongTon());

			cell = row.createCell(tenNhaCungCapvpp + 1);
			cell.setCellValue(vanPhongPham.getNhaCungCap().getTenNhaCungCap());

			cell = row.createCell(giaNhapvpp + 1);
			cell.setCellValue(vanPhongPham.getGiaNhap());

			cell = row.createCell(giaBanvpp + 1);
			cell.setCellValue(vanPhongPham.getGiaBan());

			rowIndex++;
		}

		// Auto resize column witdth
		int numberOfColumn = sheet.getRow(0).getPhysicalNumberOfCells();
		autosizeColumn(sheet, numberOfColumn);

		// Create file excel
		try (OutputStream os = new FileOutputStream(excelFilePath)) {
			workbook.write(os);
		}
	}
	
	public static void exportSach(List<Sach> listSach, String excelFilePath) throws IOException {
		// Create Workbook
		Workbook workbook = null;

		if (excelFilePath.endsWith("xlsx")) {
			workbook = new XSSFWorkbook();
		} else if (excelFilePath.endsWith("xls")) {
			workbook = new HSSFWorkbook();
		} else {
			throw new IllegalArgumentException("The specified file is not Excel file");
		}
		// Create sheet
		Sheet sheet = workbook.createSheet("Books"); // Create sheet with sheet name

		int rowIndex = 0;
		// Write header
		Row row = sheet.createRow(rowIndex);
		// Create cells
		Cell cell = row.createCell(0);
		cell.setCellValue("mã sách");

		cell = row.createCell(tenSach + 1);
		cell.setCellValue("tên sách");

		cell = row.createCell(tenTacGia + 1);
		cell.setCellValue("tên tác giả");

		cell = row.createCell(tenNhaXuatBan + 1);
		cell.setCellValue("tên nhà xuất bản");

		cell = row.createCell(tenTheLoai + 1);
		cell.setCellValue("tên thể loại");

		cell = row.createCell(soLuongTon + 1);
		cell.setCellValue("số lượng");

		cell = row.createCell(tenNhaCungCap + 1);
		cell.setCellValue("tên nhà cung cấp");

		cell = row.createCell(giaNhap + 1);
		cell.setCellValue("giá nhập");
		
		cell = row.createCell(giaBan + 1);
		cell.setCellValue("giá bán");
		// Write data
		rowIndex++;
		JSONArray jsonarray = new JSONArray();
		for (Sach sach : listSach) {
			JSONObject jsonObject = new JSONObject();
			jsonObject.put("item_id", sach.getMaSanPham());
			jsonObject.put("book_name", sach.getTenSach());
			jsonObject.put("author", sach.getTacGia().getTenTacGia());
			jsonObject.put("price", sach.getGiaNhap());
			jsonObject.put("sell_price", sach.getGiaBan());
			jsonObject.put("inventory", sach.getSoLuongTon());
			jsonarray.add(jsonObject);
			// Create row
			row = sheet.createRow(rowIndex);
			// Write data on row
			cell = row.createCell(0);
			cell.setCellValue(sach.getMaSanPham());

			cell = row.createCell(tenSach + 1);
			cell.setCellValue(sach.getTenSach());

			cell = row.createCell(tenTacGia + 1);
			cell.setCellValue(sach.getTacGia().getTenTacGia());

			cell = row.createCell(tenNhaXuatBan + 1);
			cell.setCellValue(sach.getNhaXuatBan().getTenNXB());

			cell = row.createCell(tenTheLoai + 1);
			cell.setCellValue(sach.getTheLoaiSach().getTenLoai());

			cell = row.createCell(soLuongTon + 1);
			cell.setCellValue(sach.getSoLuongTon());

			cell = row.createCell(tenNhaCungCap + 1);
			cell.setCellValue(sach.getNhaCungCap().getTenNhaCungCap());

			cell = row.createCell(giaNhap + 1);
			cell.setCellValue(sach.getGiaNhap());
			
			cell = row.createCell(giaBan + 1);
			cell.setCellValue(sach.getGiaBan());
			
			rowIndex++;
		}
		// Auto resize column witdth
		int numberOfColumn = sheet.getRow(0).getPhysicalNumberOfCells();
		autosizeColumn(sheet, numberOfColumn);

		// Create file excel
		try (OutputStream os = new FileOutputStream(excelFilePath)) {
			workbook.write(os);
		}
	}

	private static void autosizeColumn(Sheet sheet, int lastColumn) {
		for (int columnIndex = 0; columnIndex < lastColumn; columnIndex++) {
			sheet.autoSizeColumn(columnIndex);
		}
	}

	private static Object getCellValue(Cell cell) {
		CellType cellType = cell.getCellType();
		Object cellValue = null;
		switch (cellType) {
		case NUMERIC:
			cellValue = cell.getNumericCellValue();
			break;
		case STRING:
			cellValue = cell.getStringCellValue();
			break;
		default:
			cellValue = null;
			break;
		}

		return cellValue;
	}

	public int importSach(String excelFilePath) throws IOException, SQLException {
		int i = 0;
		FileInputStream fis = new FileInputStream(excelFilePath);
		Workbook workbook = null;
		if (excelFilePath.endsWith("xlsx")) {
			workbook = new XSSFWorkbook(fis);
		} else if (excelFilePath.endsWith("xls")) {
			workbook = new HSSFWorkbook(fis);
		} else {
			throw new IllegalArgumentException("The specified file is not Excel file");
		}
		Sheet sheet = workbook.getSheetAt(0);
		Iterator<Row> iterator = sheet.iterator();
		while (iterator.hasNext()) {
			Row row = iterator.next();
			if (row.getRowNum() == 0)
				continue;

			Iterator<Cell> cellIterator = row.iterator();
			Sach sach = new Sach();
			
			while (cellIterator.hasNext()) {
				Cell cell = cellIterator.next();
				Object cellValue = getCellValue(cell);
				String ma = null;
				String ten = null;
				if (cellValue == null || cellValue.toString().isEmpty())
					continue;
				
				int columnIndex = cell.getColumnIndex();
				switch (columnIndex) {
				case soLuongTon:
					sach.setSoLuongTon(Integer.parseInt(getCellValue(cell).toString().split("\\.")[0]));
					break;
				case tenNhaCungCap:
					ten = getCellValue(cell).toString().trim();
					NhaCungCap n = nhaCungCapServiceImpl.timNhaCungCap(ten);
					if (n == null) {
						try {
							ArrayList<NhaCungCap> nhaCungCaps = new ArrayList<>();
							nhaCungCaps = nhaCungCapServiceImpl.getAllListNhaCungCap();
							ma = tangMa(nhaCungCaps.get(nhaCungCaps.size() - 1).getMaNhaCungCap(), 3);
						} catch (Exception e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
						try {
							nhaCungCapServiceImpl.themNhaCungCap(new NhaCungCap(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = n.getMaNhaCungCap();
					}
					sach.setNhaCungCap(new NhaCungCap(ma, ten));
					break;
				case giaNhap:
					sach.setGiaNhap(Long.parseLong(getCellValue(cell).toString().split("\\.")[0]));
					break;
				case giaBan:
					sach.setGiaBan(Long.parseLong(getCellValue(cell).toString().split("\\.")[0]));
					break;
				case tenSach:
					sach.setTenSach(getCellValue(cell).toString());
					break;
				case tenTacGia:
					ten = getCellValue(cell).toString().trim();
					TacGia t = tacGiaServiceImpl.timTacGia(ten);
					if (t == null) {
						ma = tangMa(tacGias.get(tacGias.size() - 1).getMaTacGia(), 2);
						try {
							tacGiaServiceImpl.themTacGia(new TacGia(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = t.getMaTacGia();
					}
					sach.setTacGia(new TacGia(ma, ten));
					break;
				case tenNhaXuatBan:
					ten = getCellValue(cell).toString().trim();
					NhaXuatBan nxb = nhaXuatBanServiceImpl.timNhaXuatBan(ten);
					if (nxb == null) {
						ma = tangMa(nhaXuatBans.get(nhaXuatBans.size() - 1).getMaNXB(), 3);
						try {
							nhaXuatBanServiceImpl.themNhaXuatBan(new NhaXuatBan(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = nxb.getMaNXB();
					}
					sach.setNhaXuatBan(new NhaXuatBan(ma, ten));
					break;
				case tenTheLoai:
					ten = getCellValue(cell).toString().trim();
					TheLoaiSach tsach = theLoaiServiceImpl.timTheLoaiSach(ten);
					if (tsach == null) {
						ma = tangMa(theLoaiSachs.get(theLoaiSachs.size() - 1).getMaLoai(), 1);

						try {
							theLoaiServiceImpl.themTheLoaiSach(new TheLoaiSach(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = tsach.getMaLoai();
					}
					sach.setTheLoaiSach(new TheLoaiSach(ma, ten));
					break;
				default:
					break;
				}
				sach.setMaSanPham(tangMaSP());
				sach.setLoaiSanPham("Sách");
				sach.setDonVi("cuốn");
			}
			try {
				if (sanPhamServiceImpl.themSanPham(sach)==true) {
					i++;
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		fis.close();

		return i;
	}

	public int importVPP(String excelFilePath) throws IOException, SQLException {
		int i = 0;
		FileInputStream fis = new FileInputStream(excelFilePath);
		Workbook workbook = null;
		if (excelFilePath.endsWith("xlsx")) {
			workbook = new XSSFWorkbook(fis);
		} else if (excelFilePath.endsWith("xls")) {
			workbook = new HSSFWorkbook(fis);
		} else {
			throw new IllegalArgumentException("The specified file is not Excel file");
		}
		Sheet sheet = workbook.getSheetAt(0);
		Iterator<Row> iterator = sheet.iterator();
		while (iterator.hasNext()) {
			Row row = iterator.next();
			if (row.getRowNum() == 0)
				continue;

			Iterator<Cell> cellIterator = row.iterator();
			VanPhongPham vpp = new VanPhongPham();
			while (cellIterator.hasNext()) {
				Cell cell = cellIterator.next();
				Object cellValue = getCellValue(cell);
				String ma = null;
				String ten = null;
				if (cellValue == null || cellValue.toString().isEmpty())
					continue;

				int columnIndex = cell.getColumnIndex();
				switch (columnIndex) {
				case soLuongTonvpp:
					vpp.setSoLuongTon(Integer.parseInt(getCellValue(cell).toString().split("\\.")[0]));
					break;
				case tenNhaCungCapvpp:
					ten = getCellValue(cell).toString().trim();
					NhaCungCap n = nhaCungCapServiceImpl.timNhaCungCap(ten);
					if (n == null) {
						try {
							ArrayList<NhaCungCap> nhaCungCaps = new ArrayList<>();
							nhaCungCaps = nhaCungCapServiceImpl.getAllListNhaCungCap();
							ma = tangMa(nhaCungCaps.get(nhaCungCaps.size() - 1).getMaNhaCungCap(), 3);
						} catch (Exception e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
						try {
							nhaCungCapServiceImpl.themNhaCungCap(new NhaCungCap(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = n.getMaNhaCungCap();
					}
					vpp.setNhaCungCap(new NhaCungCap(ma, ten));
					break;
				case giaNhapvpp:
					vpp.setGiaNhap(Long.parseLong(getCellValue(cell).toString().split("\\.")[0]));
					break;
				case giaBanvpp:
					vpp.setGiaBan(Long.parseLong(getCellValue(cell).toString().split("\\.")[0]));
					break;
				case tenVanPhongPham:
					vpp.setTenVanPhongPham(getCellValue(cell).toString());
					break;
				case tenMauSac:
					ten = getCellValue(cell).toString().trim();
					MauSac mauSac = mauSacServiceImpl.timMauSac(ten);
					if (mauSac == null) {
						ArrayList<MauSac> mauSacs = null;
						try {
							mauSacs = mauSacServiceImpl.getListMauSac();
						} catch (Exception e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
						ma = tangMa(mauSacs.get(mauSacs.size() - 1).getMaMau(), 2);
						try {
							mauSacServiceImpl.themMauSac(new MauSac(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = mauSac.getMaMau();
					}
					vpp.setMauSac(new MauSac(ma, ten));
					break;
				case tenLoaiVanPhongPham:
					ten = getCellValue(cell).toString().trim();
					TheLoaiVanPhongPham tvpp = theLoaiServiceImpl.timTheLoaiVanPhongPham(ten);
					if (tvpp == null) {
						ma = tangMa(theLoaiVanPhongPhams.get(theLoaiVanPhongPhams.size() - 1).getMaLoai(), 2);

						try {
							theLoaiServiceImpl.themTheLoaiVanPhongPham(new TheLoaiVanPhongPham(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = tvpp.getMaLoai();
					}
					vpp.setLoaiVanPhongPham(new TheLoaiVanPhongPham(ma, ten));
					break;
				case tenNhaSanXuat:
					ten = getCellValue(cell).toString().trim();
					NhaSanXuat nhaSanXuat = nhaSanXuatServiceImpl.timNhaSanXuat(ten);
					if (nhaSanXuat == null) {
						ma = tangMa(nhaSanXuats.get(nhaSanXuats.size() - 1).getMaNhaSX(), 3);

						try {
							nhaSanXuatServiceImpl.themNhaSanXuat(new NhaSanXuat(ma, ten));
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					} else {
						ma = nhaSanXuat.getMaNhaSX();
					}
					vpp.setNhaSanXuat(new NhaSanXuat(ma, ten));
					break;
				default:
					break;
				}
				vpp.setMaSanPham(tangMaSP());
				vpp.setLoaiSanPham("VPP");
				vpp.setDonVi("cái");
			}
			try {
				if (sanPhamServiceImpl.themSanPham(vpp)==true) {
					i++;
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		fis.close();

		return i;
	}
	
	public String tangMa(String maHT, int indexLastAlphabet) {
		String s = maHT;
		int n = Integer.parseInt(s.substring(indexLastAlphabet).trim());
		if ((n + 1) % 10 == 0) {
			s = s.replaceAll("0" + n + "", n + 1 + "");
		} else
			s = s.replaceAll(n + "", n + 1 + "");
		return s;
	}
	
}
