/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import entity.KhachHang;
import entity.NhanVien;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import service_impl.KhachHangServiceImpl;
/**
 *
 * @author Student
 */
public class Pnl_QuanLyKhachHang extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form pnl_QuanLyKhachHang
     */
    public Pnl_QuanLyKhachHang() {
        initComponents();
        tblQuanLyKHACHHANG.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				int i = tblQuanLyKHACHHANG.getSelectedRow();
		        
		        txtMaKhachHang.setText(tableModel_KhachHang.getValueAt(i, 1).toString());
		        txtHoVaTen.setText(tableModel_KhachHang.getValueAt(i, 2).toString());
		        if (tableModel_KhachHang.getValueAt(i, 3).toString().equals("Nam")) {
		        
					rdoNam.setSelected(true);
					rdoNu.setSelected(false);
				}
					else {	
					rdoNam.setSelected(false);
					rdoNu.setSelected(true);
				}
				java.util.Date ngaySinh;
				try {
					ngaySinh = new SimpleDateFormat("yyyy-MM-dd").parse(tableModel_KhachHang.getValueAt(i, 4).toString());
					dcNgaySinh.setDate(ngaySinh);
				} catch (ParseException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
		        txtSoDienThoai.setText(tableModel_KhachHang.getValueAt(i, 5).toString());
		        txtDiaChi.setText(tableModel_KhachHang.getValueAt(i, 6).toString());
		        txtEmail.setText(tableModel_KhachHang.getValueAt(i, 7).toString());
		        		
			}
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTenManHinh = new javax.swing.JLabel();
        pnlBangDuLieuVaChucNang = new javax.swing.JPanel();
        sc_tbl_QLKH = new javax.swing.JScrollPane();
        tblQuanLyKHACHHANG = new javax.swing.JTable();
        pnlChucNang = new javax.swing.JPanel();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnNhapFile = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        pnl_ThongTinKhachHang = new javax.swing.JPanel();
        pnl_TTKHHead = new javax.swing.JPanel();
        lbl_TTKHHead = new javax.swing.JLabel();
        pnl_CTTTKH = new javax.swing.JPanel();
        lblMaKhachHang = new javax.swing.JLabel();
        lblHoVaTen = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtSoDienThoai = new javax.swing.JTextField();
        txtMaKhachHang = new javax.swing.JTextField();
        dcNgaySinh = new com.toedter.calendar.JDateChooser();
        txtHoVaTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1543, 1086));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(java.awt.Color.lightGray);

        lblTenManHinh.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblTenManHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenManHinh.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTenManHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 1543, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(lblTenManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBangDuLieuVaChucNang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        String header_row[] = { "STT", "Mã khách hàng", "Họ và tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Địa chỉ", "Email" };
        tableModel_KhachHang = new DefaultTableModel(header_row, 0);
        tblQuanLyKHACHHANG = new JTable(tableModel_KhachHang);
        sc_tbl_QLKH.setViewportView(tblQuanLyKHACHHANG);
        if (tblQuanLyKHACHHANG.getColumnModel().getColumnCount() > 0) {
        	tblQuanLyKHACHHANG.getColumnModel().getColumn(0);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(1);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(2);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(3);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(4);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(5);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(6);
    		tblQuanLyKHACHHANG.getColumnModel().getColumn(7);
        }
     
        try {
			DocDuLieuTuArray();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

        pnlChucNang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(this);
      

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(this);
 

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this);

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this);

        btnNhapFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhapFile.setText("Nhập file");
        btnNhapFile.addActionListener(this);

        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXuatFile.setText("Xuất file");
        btnXuatFile.addActionListener(this);
 

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnNhapFile, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnNhapFile)
                    .addComponent(btnXuatFile))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBangDuLieuVaChucNangLayout = new javax.swing.GroupLayout(pnlBangDuLieuVaChucNang);
        pnlBangDuLieuVaChucNang.setLayout(pnlBangDuLieuVaChucNangLayout);
        pnlBangDuLieuVaChucNangLayout.setHorizontalGroup(
            pnlBangDuLieuVaChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc_tbl_QLKH, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
            .addComponent(pnlChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBangDuLieuVaChucNangLayout.setVerticalGroup(
            pnlBangDuLieuVaChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBangDuLieuVaChucNangLayout.createSequentialGroup()
                .addComponent(sc_tbl_QLKH, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlBangDuLieuVaChucNang, java.awt.BorderLayout.LINE_START);

        pnl_ThongTinKhachHang.setLayout(new java.awt.BorderLayout());

        pnl_TTKHHead.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_TTKHHead.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TTKHHead.setText("Thông Tin Khách Hàng");

        javax.swing.GroupLayout pnl_TTKHHeadLayout = new javax.swing.GroupLayout(pnl_TTKHHead);
        pnl_TTKHHead.setLayout(pnl_TTKHHeadLayout);
        pnl_TTKHHeadLayout.setHorizontalGroup(
            pnl_TTKHHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(pnl_TTKHHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_TTKHHeadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_TTKHHead)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_TTKHHeadLayout.setVerticalGroup(
            pnl_TTKHHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_TTKHHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_TTKHHeadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_TTKHHead)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnl_ThongTinKhachHang.add(pnl_TTKHHead, java.awt.BorderLayout.PAGE_START);

        lblMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaKhachHang.setText("Mã khách hàng");

        lblHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoVaTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoVaTen.setText("Họ và tên");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiTinh.setText("Giới tính");

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgaySinh.setText("Ngày sinh");

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoDienThoai.setText("Số điện thoại");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaChi.setText("Địa chỉ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email");

        rdoNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoNam.setText("Nam");
        rdoNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rdoNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        

        txtMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaKhachHang.setEditable(false);

        dcNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
       
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
     

        javax.swing.GroupLayout pnl_CTTTKHLayout = new javax.swing.GroupLayout(pnl_CTTTKH);
        pnl_CTTTKH.setLayout(pnl_CTTTKHLayout);
        pnl_CTTTKHLayout.setHorizontalGroup(
            pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rdoNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoNu)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                        .addComponent(lblMaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                        .addComponent(lblSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
            .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
                        .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                                        .addComponent(lblHoVaTen, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)))))
                        .addGap(30, 30, 30))
                    .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
                        .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(txtHoVaTen, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(dcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTTTKHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_CTTTKHLayout.setVerticalGroup(
            pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CTTTKHLayout.createSequentialGroup()
            		.addGap(40, 40, 40)
                    .addComponent(lblMaKhachHang)
                    .addGap(12, 12, 12)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(lblHoVaTen)
                    .addGap(12, 12, 12)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(lblGioiTinh)
                    .addGap(20, 20, 20)
                    .addGroup(pnl_CTTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoNam)
                        .addComponent(rdoNu))
                    .addGap(22, 22, 22)
                    .addComponent(lblNgaySinh)
                    .addGap(12, 12, 12)
                    .addComponent(dcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(lblSoDienThoai)
                    .addGap(12, 12, 12)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(lblDiaChi)
                    .addGap(12, 12, 12)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(lblEmail)
                    .addGap(12, 12, 12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE))
        );

        pnl_CTTTKHLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcNgaySinh, txtDiaChi, txtEmail, txtHoVaTen, txtMaKhachHang, txtSoDienThoai});

        pnl_ThongTinKhachHang.add(pnl_CTTTKH, java.awt.BorderLayout.CENTER);

        add(pnl_ThongTinKhachHang, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNhapFile;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private com.toedter.calendar.JDateChooser dcNgaySinh;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoVaTen;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenManHinh;
    private javax.swing.JLabel lbl_TTKHHead;
    private javax.swing.JPanel pnlBangDuLieuVaChucNang;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnl_CTTTKH;
    private javax.swing.JPanel pnl_TTKHHead;
    private javax.swing.JPanel pnl_ThongTinKhachHang;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JScrollPane sc_tbl_QLKH;
    private javax.swing.JTable tblQuanLyKHACHHANG;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSoDienThoai;

//    private javaswingdev.FontAwesomeIcon icoCapNhat;
//    private javaswingdev.FontAwesomeIcon icoLamMoi;
//    private javaswingdev.FontAwesomeIcon icoThem;
//    private javaswingdev.FontAwesomeIcon icoXoa;
//    private javaswingdev.FontAwesomeIcon icoXuatFile;
//    private javaswingdev.FontAwesomeIcon iconNhapFile;
    private KhachHangServiceImpl iKhachHang;
    private List<KhachHang> dsKhachHang;
    private DefaultTableModel tableModel_KhachHang;
    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        try{
            Object obj = e.getSource();
            if(obj.equals(btnThem)){
                if(btnThem.getText().equals("Xác nhận")){
                    btnCapNhat.setEnabled(true);
                    btnXoa.setEnabled(true);
                    if(KiemTraDauVaoKhiThem()==0){
                        int ds = JOptionPane.showConfirmDialog(this, "Bạn có chắc thêm khách hàng này ?", "Thêm khách hàng", JOptionPane.YES_NO_OPTION);
                        if(ds==0){
                            ThemKhachHang();
                        }
                    }
                }else{
                    txtMaKhachHang.setText(tangMaKH());
                    btnCapNhat.setEnabled(false);
                    btnXoa.setEnabled(false);
                    btnThem.setText("Xác nhận");
                }
            }else if(obj.equals(btnCapNhat)){
                if(tblQuanLyKHACHHANG.getSelectedRow()==-1){
                    JOptionPane.showMessageDialog(this, "Phải chọn dòng trước khi cập nhật");
                }else{
                    int ds = JOptionPane.showConfirmDialog(this, "Bạn có chắc cập nhật khách hàng này ?", "Cập nhật khách hàng", JOptionPane.YES_NO_OPTION);
                    if(ds==0){
                        capNhatKH();
                    }
                }
            }else if(obj.equals(btnXoa)){
                if(tblQuanLyKHACHHANG.getSelectedRow()==-1){
                    JOptionPane.showMessageDialog(this, "Phải chọn dòng trước khi xóa");
                }else{
                    int ds = JOptionPane.showConfirmDialog(this, "Bạn có chắc xóa khách hàng này ?", "Xóa khách hàng", JOptionPane.YES_NO_OPTION);
                    if(ds==0){
                        xoaKhachHang();
                    }
                }
            }else if(obj.equals(btnLamMoi)){
                clear_form();
                xoaHetDuLieu();
                DocDuLieuTuArray();
            }
        }catch(Exception e2){
            e2.printStackTrace();
        }
    }

    
    public void DocDuLieuTuArray () throws SQLException{
        iKhachHang = new KhachHangServiceImpl();
        dsKhachHang = iKhachHang.getDSKhachHang();
        
        int i =1;
        xoaHetDuLieu();
        for (KhachHang kh : dsKhachHang){
        	if(kh.isTrangThai()) {
        		 Object[] ob = { i++, kh.getMaKH(), kh.getHoTenKH() , kh.isGioiTinh() != true ? "Nam" : "Nữ", kh.getNgaySinh(),
                         kh.getSDT(),kh.getDiaChi(), kh.getEmail()};
        		 tableModel_KhachHang.addRow(ob);
        		}
           }
    }
    
    
    public KhachHang revertKhachHangFromTextfields() {
    	String maKH = txtMaKhachHang.getText();
    	String tenKH = txtHoVaTen.getText();
    	boolean gioiTinh = rdoNu.isSelected();
                
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    	String day = sdf.format(dcNgaySinh.getDate());
    	String date[] = day.split("-");
    	int nam = Integer.parseInt(date[0]);
    	int thang = Integer.parseInt(date[1]);
    	int ngay = Integer.parseInt(date[2]);
    	LocalDate lcDate = LocalDate.of(nam, thang, ngay);
                
		String sdt = txtSoDienThoai.getText();
		String diaChi = txtDiaChi.getText();
		String email = txtEmail.getText();
		
		KhachHang kh = new KhachHang(maKH, tenKH, gioiTinh, lcDate, sdt, diaChi, email);
		return kh;
    }
        
    public void ThemKhachHang(){
        KhachHang kh = revertKhachHangFromTextfields();
        if(kh==null){
            return;
        }
        
        try {
            if(iKhachHang.themKhachHang(kh) == 0){
                JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            }else{
                JOptionPane.showMessageDialog(null,"Thêm khách hàng thành công" );
                xoaHetDuLieu();
                clear_form();
                DocDuLieuTuArray();
                btnThem.setText("Thêm");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void xoaKhachHang(){
        int i = tblQuanLyKHACHHANG.getSelectedRow();
        String maKH = (String) tblQuanLyKHACHHANG.getValueAt(i, 1);
        try{
            if(iKhachHang.xoaKhachHang(maKH)==0){
                JOptionPane.showMessageDialog(null, "Xóa không thành công!");
            }else{
                JOptionPane.showMessageDialog(null, "Xóa thành công!");
//                tableModel_KhachHang.removeRow(i);
                DocDuLieuTuArray();
                clear_form();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void editOnRow() {
		int row = tblQuanLyKHACHHANG.getSelectedRow();
		KhachHang kh = revertKhachHangFromTextfields();

		tblQuanLyKHACHHANG.setValueAt(kh.getMaKH(), row, 1);
		tblQuanLyKHACHHANG.setValueAt(kh.getHoTenKH(), row, 2);
		tblQuanLyKHACHHANG.setValueAt(kh.isGioiTinh() != true ? "Nam" : "Nữ", row, 3);
		tblQuanLyKHACHHANG.setValueAt(kh.getNgaySinh(), row, 4);
		tblQuanLyKHACHHANG.setValueAt(kh.getSDT(), row, 5);
		tblQuanLyKHACHHANG.setValueAt(kh.getDiaChi(), row, 6);
		tblQuanLyKHACHHANG.setValueAt(kh.getEmail(), row, 7);
		System.out.println(row);

	}
    
    public int KiemTraDauVaoKhiThem() {
		String tenKH = txtHoVaTen.getText();
		if(tenKH.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập họ tên!");
			txtHoVaTen.requestFocus();
			return 1;
		}
		if(dcNgaySinh.getDate() == null) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày sinh !");
			dcNgaySinh.requestFocus();
			return 1;
		}
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		String day = sdf.format(dcNgaySinh.getDate());
		String date[] = day.split("-");
		int nam = Integer.parseInt(date[0]);
		LocalDate date2 = LocalDate.now();
		if(date2.getYear() - nam < 19) {
			JOptionPane.showMessageDialog(null, "Tuổi phải trên 19!");
			return 1;
		}
		String sdt = txtSoDienThoai.getText();
		if(sdt.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại !");
			txtSoDienThoai.requestFocus();
			return 1;
		}
		String diaChi = txtDiaChi.getText();
		if(diaChi.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập địa chỉ !");
			txtDiaChi.requestFocus();
			return 1;
		}
		String email = txtEmail.getText();
		if(email.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập email !");
			txtEmail.requestFocus();
			return 1;
		}
		
		return 0;
    }
    
    public void clear_form(){
        txtMaKhachHang.setText("");
	txtHoVaTen.setText("");
	rdoNam.setSelected(false);
	rdoNu.setSelected(false);
	dcNgaySinh.setDate(null);
	txtSoDienThoai.setText("");
	txtDiaChi.setText("");
	txtEmail.setText("");
    }
    
    public void xoaHetDuLieu(){
        DefaultTableModel dt = (DefaultTableModel) tblQuanLyKHACHHANG.getModel();
        dt.getDataVector().removeAllElements();
    }
     
//    public void setValueForm(int i){  
//        txtMaKhachHang.setText(tblQuanLyKHACHHANG.getValueAt(i, 1)+"");
//        txtHoVaTen.setText(tblQuanLyKHACHHANG.getValueAt(i, 2)+"");
//        String gioiTinh = tblQuanLyKHACHHANG.getValueAt(i, 3)+"";
//        
//        if (gioiTinh.equals("Nam")){
//            rdoNam.isSelected();
//        }else{
//            rdoNu.isSelected();
//        }
//        
//        Date ngaySinh;
//        try{
//            ngaySinh = new SimpleDateFormat("yyyy-MM-dd").parse(tblQuanLyKHACHHANG.getValueAt(i, 4)+"");
//            dcNgaySinh.setDate(ngaySinh);
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//        
//        txtSoDienThoai.setText(tblQuanLyKHACHHANG.getValueAt(i, 5)+"");
//		txtDiaChi.setText(tblQuanLyKHACHHANG.getValueAt(i, 6)+"");
//		txtEmail.setText(tblQuanLyKHACHHANG.getValueAt(i, 7)+ "");
//        
//        
//    }
    
    public String tangMaKH() {
        int i = tableModel_KhachHang.getRowCount();
        System.out.println(i-1);
        String maKH = (String) tblQuanLyKHACHHANG.getValueAt(i-1, 1);
        maKH = maKH.split("KH")[1].trim();
        int num = Integer.parseInt(maKH)+1;
        if(num<10){
            maKH = "KH00"+num;
        }else{
            maKH = "KH0"+num;
        }
        return maKH;
                
    }
    
    public void capNhatKH(){
        KhachHang nv = revertKhachHangFromTextfields();
	if(nv ==null)
            return;
	try {
            if(iKhachHang.capNhatKhachHang(nv) == 0) {
		JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            }else {
            xoaHetDuLieu();
	    clear_form();
	    DocDuLieuTuArray();
            }
        } catch (SQLException e) {
            
        }
    }
}   
    
    

